[workspace]
members = ["apps/desktop", "crates/dawn-language", "crates/dawn-project-io", "crates/dawn-runtime"]
resolver = "2"

[workspace.package]
edition = "2024"
rust-version = "1.96"
version = "0.1.0"

[workspace.dependencies]
bytemuck = { version = "1.25.0", features = ["derive"] }
camino = "1.2.4"
criterion = "0.8.2"
dawn-language = { path = "crates/dawn-language" }
dawn-project-io = { path = "crates/dawn-project-io" }
dawn-runtime = { path = "crates/dawn-runtime" }
glam = "0.33.2"
indexmap = "2.14.0"
kira = "0.12.1"
marked-yaml = "0.8.0"
rfd = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1"
specta = { version = "2.0.0-rc.25", features = ["derive"] }
specta-typescript = "0.0.12"
tauri = { version = "2.11.3", features = ["protocol-asset", "unstable"] }
tauri-build = "2.6.3"
tauri-specta = { version = "2.0.0-rc.25", features = ["derive", "typescript"] }
tempfile = "3.27.0"
wgpu = { version = "29.0.3", default-features = false, features = ["std", "parking_lot", "metal", "gles", "vulkan", "wgsl", "webgpu"] }
yaml_serde = "0.10.4"
