use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use clap::Parser;

mod spec;

use spec::{Grammar, PatternItem, TriviaPolicy};

#[derive(Debug, Parser)]
struct Args {
    #[arg(long, conflicts_with = "check")]
    write: bool,
    #[arg(long, conflicts_with = "write")]
    check: bool,
    #[arg(long)]
    grammar: PathBuf,
    #[arg(long)]
    out: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();
    if !args.write && !args.check {
        bail!("pass --write or --check");
    }

    let grammar = Grammar::load(&args.grammar)?;
    grammar.validate()?;
    let files = generate(&grammar);

    if args.write {
        fs::create_dir_all(&args.out)?;
        for (name, contents) in files {
            let path = args.out.join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)?;
        }
        return Ok(());
    }

    let mut stale = Vec::new();
    for (name, expected) in files {
        let path = args.out.join(name);
        let actual = fs::read_to_string(&path)
            .with_context(|| format!("failed to read generated file {}", path.display()))?;
        if actual != expected {
            stale.push(name);
        }
    }

    if !stale.is_empty() {
        bail!("generated files are stale: {}", stale.join(", "));
    }
    Ok(())
}

pub fn generate(grammar: &Grammar) -> Vec<(&'static str, String)> {
    vec![
        ("src/generated/mod.rs", gen_mod()),
        ("src/generated/diagnostic.rs", gen_diagnostic(grammar)),
        ("src/generated/kind.rs", gen_kind(grammar)),
        ("src/generated/lexer.rs", gen_lexer(grammar)),
        ("src/generated/parser.rs", gen_parser(grammar)),
        ("src/generated/ast.rs", gen_ast(grammar)),
    ]
}

fn header() -> &'static str {
    "// @generated by syntax-gen. Do not edit by hand.\n\n"
}

fn gen_mod() -> String {
    let mut out = String::from(header());
    out.push_str("pub mod ast;\n");
    out.push_str("pub mod diagnostic;\n");
    out.push_str("pub mod kind;\n");
    out.push_str("pub mod lexer;\n");
    out.push_str("pub mod parser;\n");
    out
}

fn gen_diagnostic(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum DiagnosticKind {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!("    {},\n", diagnostic.name));
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "pub const INVALID_TOKEN_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n",
        grammar.diagnostics.invalid_token
    ));
    out.push_str(&format!(
        "pub const UNEXPECTED_TOKEN_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n",
        grammar.diagnostics.unexpected_token
    ));
    out.push_str(&format!(
        "pub const UNEXPECTED_EOF_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n\n",
        grammar.diagnostics.unexpected_eof
    ));
    out.push_str("impl DiagnosticKind {\n");
    out.push_str("    pub fn message(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!(
            "            Self::{} => {:?},\n",
            diagnostic.name, diagnostic.message
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::fmt::Display for DiagnosticKind {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        f.write_str(self.message())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for DiagnosticKind {}\n");
    out
}

fn gen_kind(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    let syntax_kind = &grammar.language.syntax_kind;
    let language_type = &grammar.language.type_name;
    out.push_str(&format!("#[repr(u16)]\npub enum {syntax_kind} {{\n"));
    for name in grammar.syntax_kinds() {
        out.push_str("    ");
        out.push_str(name);
        out.push_str(",\n");
    }
    out.push_str("    Error,\n}\n\n");
    out.push_str(&format!("impl {syntax_kind} {{\n"));
    out.push_str("    pub fn is_trivia(self) -> bool {\n");
    let trivia = grammar
        .trivia_names()
        .into_iter()
        .map(|trivia| format!("Self::{trivia}"))
        .collect::<Vec<_>>();
    if trivia.is_empty() {
        out.push_str("        false\n");
    } else {
        out.push_str("        matches!(self, ");
        out.push_str(&trivia.join(" | "));
        out.push_str(")\n");
    }
    out.push_str("    }\n}\n\n");
    out.push_str(&format!(
        "impl From<{syntax_kind}> for rowan::SyntaxKind {{\n"
    ));
    out.push_str(&format!("    fn from(kind: {syntax_kind}) -> Self {{\n"));
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str(&format!("pub enum {language_type} {{}}\n\n"));
    out.push_str(&format!("impl rowan::Language for {language_type} {{\n"));
    out.push_str(&format!("    type Kind = {syntax_kind};\n\n"));
    out.push_str("    fn kind_from_raw(raw: rowan::SyntaxKind) -> Self::Kind {\n");
    out.push_str(&format!(
        "        assert!(raw.0 <= {syntax_kind}::Error as u16);\n"
    ));
    out.push_str(&format!(
        "        unsafe {{ std::mem::transmute::<u16, {syntax_kind}>(raw.0) }}\n"
    ));
    out.push_str("    }\n\n");
    out.push_str("    fn kind_to_raw(kind: Self::Kind) -> rowan::SyntaxKind {\n");
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n}\n");
    out
}

fn gen_lexer(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("use std::sync::OnceLock;\n\n");
    out.push_str("use regex::Regex;\n\n");
    out.push_str("use crate::diagnostic::{Diagnostic, DiagnosticKind};\n");
    out.push_str("use crate::generated::diagnostic::INVALID_TOKEN_DIAGNOSTIC;\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n\n",
        grammar.language.syntax_kind
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub struct LexToken {\n");
    out.push_str("    pub kind: SyntaxKind,\n");
    out.push_str("    pub range: std::ops::Range<usize>,\n");
    out.push_str("    pub text: String,\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("enum Matcher {\n");
    out.push_str("    Regex(usize),\n");
    out.push_str("    Delimited { start: &'static str, end: &'static str },\n");
    out.push_str("    Literal(&'static str),\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("struct Rule {\n");
    out.push_str("    kind: SyntaxKind,\n");
    out.push_str("    matcher: Matcher,\n");
    out.push_str("    skip: bool,\n");
    out.push_str("    diagnostic: Option<DiagnosticKind>,\n");
    out.push_str("}\n\n");

    let mut regexes = Vec::new();
    let mut rules = Vec::new();
    for token in &grammar.tokens.rules {
        let matcher = if let Some(pattern) = &token.regex {
            let index = regexes.len();
            regexes.push(pattern.clone());
            format!("Matcher::Regex({index})")
        } else if let Some(literal) = &token.literal {
            format!("Matcher::Literal({literal:?})")
        } else {
            format!(
                "Matcher::Delimited {{ start: {:?}, end: {:?} }}",
                token.start.as_ref().expect("validated"),
                token.end.as_ref().expect("validated")
            )
        };
        rules.push(format!(
            "    Rule {{ kind: SyntaxKind::{}, matcher: {}, skip: {}, diagnostic: {} }},\n",
            token.name,
            matcher,
            matches!(token.trivia, TriviaPolicy::Skip),
            diagnostic_option(token.diagnostic.as_deref())
        ));
    }

    out.push_str("const REGEX_PATTERNS: &[&str] = &[\n");
    for pattern in regexes {
        out.push_str(&format!("    {:?},\n", format!("^(?:{pattern})")));
    }
    out.push_str("];\n\n");
    out.push_str("const RULES: &[Rule] = &[\n");
    for rule in rules {
        out.push_str(&rule);
    }
    out.push_str("];\n\n");
    out.push_str(include_str!("templates/lexer.rs"));
    out
}

fn diagnostic_option(name: Option<&str>) -> String {
    name.map(|name| format!("Some(DiagnosticKind::{name})"))
        .unwrap_or_else(|| "None".to_string())
}

fn gen_parser(grammar: &Grammar) -> String {
    let grammar_sets = GrammarSets::new(grammar);
    let mut out = String::from(header());
    out.push_str("use rowan::{GreenNode, GreenNodeBuilder};\n\n");
    out.push_str("use crate::diagnostic::Diagnostic;\n");
    out.push_str("use crate::generated::diagnostic::{UNEXPECTED_EOF_DIAGNOSTIC, UNEXPECTED_TOKEN_DIAGNOSTIC};\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n",
        grammar.language.syntax_kind
    ));
    out.push_str("use crate::generated::lexer::LexToken;\n\n");

    for (name, tokens) in &grammar_sets.named_token_slices {
        emit_token_slice(&mut out, name, tokens);
    }
    out.push_str("fn token_set(index: usize) -> &'static [SyntaxKind] {\n");
    out.push_str("    match index {\n");
    for index in 0..grammar.syntax.token_sets.len() {
        out.push_str(&format!("        {index} => TOKEN_SET_{index},\n"));
    }
    out.push_str("        _ => unreachable!(\"generated parser requested invalid token set\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    for choice in &grammar_sets.choices {
        for alt in &choice.alternatives {
            emit_token_slice(&mut out, &alt.first_name, &alt.first);
        }
        out.push_str(&format!("static {}: &[Alternative] = &[\n", choice.name));
        for alt in &choice.alternatives {
            out.push_str(&format!(
                "    Alternative {{ item: {}, first: {} }},\n",
                alt.item_expr, alt.first_name
            ));
        }
        out.push_str("];\n\n");
    }

    for rule in &grammar_sets.rules {
        emit_token_slice(&mut out, &rule.first_name, &rule.first);
        out.push_str(&format!("static {}: &[Item] = &[\n", rule.items_name));
        for item in &rule.items {
            out.push_str(&format!("    {},\n", item));
        }
        out.push_str("];\n\n");
    }

    out.push_str("const ENTRY_RULE: usize = ");
    out.push_str(&grammar_sets.entry_rule.to_string());
    out.push_str(";\n\n");
    out.push_str("static RULES: &[Rule] = &[\n");
    for rule in &grammar_sets.rules {
        out.push_str(&format!(
            "    Rule {{ kind: SyntaxKind::{}, items: {}, first: {} }},\n",
            rule.kind, rule.items_name, rule.first_name
        ));
    }
    out.push_str("];\n\n");

    emit_expression_tables(&mut out, grammar, &grammar_sets);

    out.push_str(include_str!("templates/parser.rs"));
    out
}

fn emit_expression_tables(out: &mut String, grammar: &Grammar, grammar_sets: &GrammarSets) {
    out.push_str("const PREFIX_BINDING_POWER: u8 = 200;\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct Expression { root: SyntaxKind, atoms: &'static [ExprAtom], prefix: &'static [PrefixOp], infix: &'static [InfixOp], postfix: &'static [PostfixOp] }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct ExprAtom { item: Item, first: &'static [SyntaxKind] }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct PrefixOp { token: SyntaxKind, node: SyntaxKind }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str(
        "struct InfixOp { token: SyntaxKind, node: SyntaxKind, left_bp: u8, right_bp: u8 }\n\n",
    );
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct PostfixOp { node: SyntaxKind, items: &'static [Item], first: &'static [SyntaxKind] }\n\n");

    for (expr_index, expression) in grammar.expressions.items.iter().enumerate() {
        for (atom_index, atom) in expression.atoms.iter().enumerate() {
            let first = if let Some(token) = &atom.token {
                BTreeSet::from([token.clone()])
            } else {
                let node = atom.node.as_ref().expect("validated");
                grammar_sets.rule_first(node).clone()
            };
            emit_token_slice(
                out,
                &format!("EXPR_{expr_index}_ATOM_{atom_index}_FIRST"),
                &first,
            );
        }
        for (postfix_index, postfix) in expression.postfix.iter().enumerate() {
            let first = first_of_sequence(
                &postfix.pattern,
                &grammar_sets.first,
                &grammar_sets.nullable_rules,
                &grammar_sets.rule_indices,
                &grammar_sets.token_sets,
                &grammar_sets.token_set_indices,
            );
            emit_token_slice(
                out,
                &format!("EXPR_{expr_index}_POSTFIX_{postfix_index}_FIRST"),
                &first,
            );
            out.push_str(&format!(
                "static EXPR_{expr_index}_POSTFIX_{postfix_index}_ITEMS: &[Item] = &[\n"
            ));
            let parent_follow = BTreeSet::new();
            let mut repeat_stops = BTreeMap::new();
            for (item_index, item) in postfix.pattern.iter().enumerate() {
                let stop = item_follow_at(
                    &postfix.pattern,
                    item_index,
                    &parent_follow,
                    &grammar_sets.first,
                    &grammar_sets.nullable_rules,
                    &grammar_sets.rule_indices,
                    &grammar_sets.token_sets,
                    &grammar_sets.token_set_indices,
                );
                let expr = item_expr(
                    item,
                    usize::MAX - expr_index,
                    item_index,
                    &stop,
                    &mut Vec::new(),
                    &mut repeat_stops,
                    &grammar_sets.first,
                    &grammar_sets.nullable_rules,
                    &grammar_sets.rule_indices,
                    &grammar_sets.token_sets,
                    &grammar_sets.token_set_indices,
                    &grammar_sets.expression_indices,
                );
                out.push_str(&format!("    {expr},\n"));
            }
            out.push_str("];\n\n");
            for (name, tokens) in repeat_stops {
                emit_token_slice(out, &name, &tokens);
            }
        }

        out.push_str(&format!(
            "static EXPR_{expr_index}_ATOMS: &[ExprAtom] = &[\n"
        ));
        for (atom_index, atom) in expression.atoms.iter().enumerate() {
            let item = if let Some(token) = &atom.token {
                format!("Item::Token(SyntaxKind::{token})")
            } else {
                let node = atom.node.as_ref().expect("validated");
                format!(
                    "Item::Node({})",
                    grammar_sets.rule_indices.get(node).expect("validated")
                )
            };
            out.push_str(&format!(
                "    ExprAtom {{ item: {item}, first: EXPR_{expr_index}_ATOM_{atom_index}_FIRST }},\n"
            ));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "static EXPR_{expr_index}_PREFIX: &[PrefixOp] = &[\n"
        ));
        for prefix in &expression.prefix {
            out.push_str(&format!(
                "    PrefixOp {{ token: SyntaxKind::{}, node: SyntaxKind::{} }},\n",
                prefix.token, prefix.node
            ));
        }
        out.push_str("];\n\n");

        let mut precedence = BTreeMap::<String, u8>::new();
        for infix in &expression.infix {
            if !precedence.contains_key(&infix.precedence) {
                let bp = ((precedence.len() + 1) * 10) as u8;
                precedence.insert(infix.precedence.clone(), bp);
            }
        }
        out.push_str(&format!(
            "static EXPR_{expr_index}_INFIX: &[InfixOp] = &[\n"
        ));
        for infix in &expression.infix {
            let bp = precedence[&infix.precedence];
            let (left_bp, right_bp) = if infix.associativity == "right" {
                (bp, bp)
            } else {
                (bp, bp + 1)
            };
            out.push_str(&format!(
                "    InfixOp {{ token: SyntaxKind::{}, node: SyntaxKind::{}, left_bp: {left_bp}, right_bp: {right_bp} }},\n",
                infix.token, infix.node
            ));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "static EXPR_{expr_index}_POSTFIX: &[PostfixOp] = &[\n"
        ));
        for (postfix_index, postfix) in expression.postfix.iter().enumerate() {
            out.push_str(&format!(
                "    PostfixOp {{ node: SyntaxKind::{}, items: EXPR_{expr_index}_POSTFIX_{postfix_index}_ITEMS, first: EXPR_{expr_index}_POSTFIX_{postfix_index}_FIRST }},\n",
                postfix.node
            ));
        }
        out.push_str("];\n\n");
    }

    out.push_str("static EXPRESSIONS: &[Expression] = &[\n");
    for (expr_index, expression) in grammar.expressions.items.iter().enumerate() {
        out.push_str(&format!(
            "    Expression {{ root: SyntaxKind::{}, atoms: EXPR_{expr_index}_ATOMS, prefix: EXPR_{expr_index}_PREFIX, infix: EXPR_{expr_index}_INFIX, postfix: EXPR_{expr_index}_POSTFIX }},\n",
            expression.root_node
        ));
    }
    out.push_str("];\n\n");
}

fn emit_token_slice(out: &mut String, name: &str, tokens: &BTreeSet<String>) {
    out.push_str(&format!("static {name}: &[SyntaxKind] = &[\n"));
    for token in tokens {
        out.push_str(&format!("    SyntaxKind::{token},\n"));
    }
    out.push_str("];\n\n");
}

struct GrammarSets {
    entry_rule: usize,
    rules: Vec<GeneratedRule>,
    choices: Vec<GeneratedChoice>,
    named_token_slices: BTreeMap<String, BTreeSet<String>>,
    rule_indices: HashMap<String, usize>,
    token_set_indices: HashMap<String, usize>,
    token_sets: Vec<BTreeSet<String>>,
    first: Vec<BTreeSet<String>>,
    nullable_rules: Vec<bool>,
    expression_indices: HashMap<String, usize>,
}

struct GeneratedRule {
    kind: String,
    items_name: String,
    first_name: String,
    items: Vec<String>,
    first: BTreeSet<String>,
}

struct GeneratedChoice {
    name: String,
    alternatives: Vec<GeneratedAlternative>,
}

struct GeneratedAlternative {
    item_expr: String,
    first_name: String,
    first: BTreeSet<String>,
}

impl GrammarSets {
    fn new(grammar: &Grammar) -> Self {
        let rule_indices = grammar
            .syntax
            .rules
            .iter()
            .enumerate()
            .map(|(index, rule)| (rule.name.clone(), index))
            .collect::<HashMap<_, _>>();
        let token_set_indices = grammar
            .syntax
            .token_sets
            .iter()
            .enumerate()
            .map(|(index, set)| (set.name.clone(), index))
            .collect::<HashMap<_, _>>();
        let all_tokens = grammar
            .token_names()
            .into_iter()
            .map(str::to_string)
            .collect::<BTreeSet<_>>();
        let token_sets = grammar
            .syntax
            .token_sets
            .iter()
            .map(|set| {
                let mut tokens = if set.include.as_deref() == Some("all_tokens") {
                    all_tokens.clone()
                } else {
                    set.tokens.iter().cloned().collect::<BTreeSet<_>>()
                };
                for token in &set.exclude {
                    tokens.remove(token);
                }
                tokens
            })
            .collect::<Vec<_>>();
        let expression_indices = grammar
            .expressions
            .items
            .iter()
            .enumerate()
            .map(|(index, expression)| (expression.name.clone(), index))
            .collect::<HashMap<_, _>>();

        let mut nullable_rules = vec![false; grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            for (index, rule) in grammar.syntax.rules.iter().enumerate() {
                if !nullable_rules[index]
                    && pattern_nullable_with(
                        &rule.pattern,
                        &nullable_rules,
                        &rule_indices,
                        &token_set_indices,
                    )
                {
                    nullable_rules[index] = true;
                    changed = true;
                }
            }
            if !changed {
                break;
            }
        }

        let mut first = vec![BTreeSet::new(); grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            for (index, rule) in grammar.syntax.rules.iter().enumerate() {
                let item_first = first_of_sequence(
                    &rule.pattern,
                    &first,
                    &nullable_rules,
                    &rule_indices,
                    &token_sets,
                    &token_set_indices,
                );
                changed |= extend_set(&mut first[index], item_first);
            }
            if !changed {
                break;
            }
        }

        let mut follow = vec![BTreeSet::new(); grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            for (rule_index, rule) in grammar.syntax.rules.iter().enumerate() {
                changed |= collect_follow(
                    &rule.pattern,
                    &follow[rule_index].clone(),
                    &mut follow,
                    &first,
                    &nullable_rules,
                    &rule_indices,
                    &token_sets,
                    &token_set_indices,
                );
            }
            if !changed {
                break;
            }
        }

        let mut choices = Vec::new();
        let mut named_token_slices = BTreeMap::new();
        for (index, set) in grammar.syntax.token_sets.iter().enumerate() {
            named_token_slices.insert(format!("TOKEN_SET_{index}"), token_sets[index].clone());
            let _ = set;
        }

        let mut generated_rules = Vec::new();
        for (rule_index, rule) in grammar.syntax.rules.iter().enumerate() {
            let items = rule
                .pattern
                .iter()
                .enumerate()
                .map(|(item_index, item)| {
                    let stop = item_follow_at(
                        &rule.pattern,
                        item_index,
                        &follow[rule_index],
                        &first,
                        &nullable_rules,
                        &rule_indices,
                        &token_sets,
                        &token_set_indices,
                    );
                    item_expr(
                        item,
                        rule_index,
                        item_index,
                        &stop,
                        &mut choices,
                        &mut named_token_slices,
                        &first,
                        &nullable_rules,
                        &rule_indices,
                        &token_sets,
                        &token_set_indices,
                        &expression_indices,
                    )
                })
                .collect::<Vec<_>>();
            generated_rules.push(GeneratedRule {
                kind: rule.name.clone(),
                items_name: format!("RULE_{rule_index}_ITEMS"),
                first_name: format!("RULE_{rule_index}_FIRST"),
                items,
                first: first[rule_index].clone(),
            });
        }

        Self {
            entry_rule: *rule_indices.get(&grammar.syntax.entry).expect("validated"),
            rules: generated_rules,
            choices,
            named_token_slices,
            rule_indices,
            token_set_indices,
            token_sets,
            first,
            nullable_rules,
            expression_indices,
        }
    }

    fn rule_first(&self, name: &str) -> &BTreeSet<String> {
        &self.first[*self.rule_indices.get(name).expect("validated")]
    }
}

fn extend_set(target: &mut BTreeSet<String>, source: BTreeSet<String>) -> bool {
    let before = target.len();
    target.extend(source);
    target.len() != before
}

fn first_of_sequence(
    items: &[PatternItem],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
) -> BTreeSet<String> {
    let mut result = BTreeSet::new();
    for item in items {
        result.extend(first_of_item(
            item,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
        ));
        if !item_nullable_with(item, nullable_rules, rule_indices, token_set_indices) {
            break;
        }
    }
    result
}

fn first_of_item(
    item: &PatternItem,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
) -> BTreeSet<String> {
    if let Some(token) = &item.token {
        return BTreeSet::from([token.clone()]);
    }
    if let Some(node) = &item.node {
        return first[*rule_indices.get(node).expect("validated")].clone();
    }
    if let Some(repeat) = &item.repeat {
        if let Some(index) = rule_indices.get(repeat) {
            return first[*index].clone();
        }
        return token_sets[*token_set_indices.get(repeat).expect("validated")].clone();
    }
    if let Some(choice) = &item.choice {
        return choice
            .iter()
            .flat_map(|alt| {
                first_of_item(
                    alt,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                )
            })
            .collect();
    }
    if let Some(token_set) = &item.token_set {
        return token_sets[*token_set_indices.get(token_set).expect("validated")].clone();
    }
    if item.expr.is_some() {
        return BTreeSet::new();
    }
    BTreeSet::new()
}

fn pattern_nullable_with(
    pattern: &[PatternItem],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_set_indices: &HashMap<String, usize>,
) -> bool {
    pattern
        .iter()
        .all(|item| item_nullable_with(item, nullable_rules, rule_indices, token_set_indices))
}

fn item_nullable_with(
    item: &PatternItem,
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_set_indices: &HashMap<String, usize>,
) -> bool {
    if let Some(repeat) = &item.repeat {
        return rule_indices.contains_key(repeat) || token_set_indices.contains_key(repeat);
    }
    if let Some(node) = &item.node {
        return nullable_rules[*rule_indices.get(node).expect("validated")];
    }
    if let Some(choice) = &item.choice {
        return choice
            .iter()
            .any(|alt| item_nullable_with(alt, nullable_rules, rule_indices, token_set_indices));
    }
    false
}

fn item_follow_at(
    items: &[PatternItem],
    item_index: usize,
    parent_follow: &BTreeSet<String>,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
) -> BTreeSet<String> {
    let rest = &items[item_index + 1..];
    let mut item_follow = first_of_sequence(
        rest,
        first,
        nullable_rules,
        rule_indices,
        token_sets,
        token_set_indices,
    );
    if pattern_nullable_with(rest, nullable_rules, rule_indices, token_set_indices) {
        item_follow.extend(parent_follow.iter().cloned());
    }
    item_follow
}

fn collect_follow(
    items: &[PatternItem],
    parent_follow: &BTreeSet<String>,
    follow: &mut [BTreeSet<String>],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
) -> bool {
    let mut changed = false;
    for (index, item) in items.iter().enumerate() {
        let rest = &items[index + 1..];
        let mut item_follow = first_of_sequence(
            rest,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
        );
        if pattern_nullable_with(rest, nullable_rules, rule_indices, token_set_indices) {
            item_follow.extend(parent_follow.iter().cloned());
        }
        changed |= collect_follow_for_item(
            item,
            item_follow,
            follow,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
        );
    }
    changed
}

fn collect_follow_for_item(
    item: &PatternItem,
    item_follow: BTreeSet<String>,
    follow: &mut [BTreeSet<String>],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
) -> bool {
    let mut changed = false;
    if let Some(node) = &item.node {
        changed |= extend_set(
            &mut follow[*rule_indices.get(node).expect("validated")],
            item_follow,
        );
    } else if let Some(repeat) = &item.repeat {
        if let Some(rule_index) = rule_indices.get(repeat) {
            let mut repeat_follow = item_follow;
            repeat_follow.extend(first[*rule_index].iter().cloned());
            changed |= extend_set(&mut follow[*rule_index], repeat_follow);
        }
    } else if let Some(choice) = &item.choice {
        for alt in choice {
            changed |= collect_follow_for_item(
                alt,
                item_follow.clone(),
                follow,
                first,
                nullable_rules,
                rule_indices,
                token_sets,
                token_set_indices,
            );
        }
    }
    changed
}

fn item_expr(
    item: &PatternItem,
    rule_index: usize,
    item_index: usize,
    item_follow: &BTreeSet<String>,
    choices: &mut Vec<GeneratedChoice>,
    named_token_slices: &mut BTreeMap<String, BTreeSet<String>>,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
) -> String {
    if let Some(token) = &item.token {
        return format!("Item::Token(SyntaxKind::{token})");
    }
    if let Some(node) = &item.node {
        return format!("Item::Node({})", rule_indices.get(node).expect("validated"));
    }
    if let Some(repeat) = &item.repeat {
        let stop_name = format!("ITEM_{rule_index}_{item_index}_STOP");
        named_token_slices.insert(stop_name.clone(), item_follow.clone());
        if let Some(index) = rule_indices.get(repeat) {
            return format!("Item::RepeatRule {{ index: {index}, stop: {stop_name} }}");
        }
        return format!(
            "Item::RepeatTokenSet {{ index: {}, stop: {stop_name} }}",
            token_set_indices.get(repeat).expect("validated")
        );
    }
    if let Some(token_set) = &item.token_set {
        return format!(
            "Item::TokenSet({})",
            token_set_indices.get(token_set).expect("validated")
        );
    }
    if let Some(expr) = &item.expr {
        return format!(
            "Item::Expr({})",
            expression_indices.get(expr).expect("validated")
        );
    }
    if let Some(choice) = &item.choice {
        let choice_name = format!("CHOICE_{}_{}", rule_index, item_index);
        let mut seen = BTreeSet::new();
        let mut alternatives = Vec::new();
        for (alt_index, alt) in choice.iter().enumerate() {
            let alt_first = first_of_item(
                alt,
                first,
                nullable_rules,
                rule_indices,
                token_sets,
                token_set_indices,
            );
            let overlap = seen.intersection(&alt_first).cloned().collect::<Vec<_>>();
            assert!(
                overlap.is_empty(),
                "ambiguous choice in rule {rule_index}, item {item_index}: {overlap:?}"
            );
            seen.extend(alt_first.iter().cloned());
            alternatives.push(GeneratedAlternative {
                item_expr: item_expr(
                    alt,
                    rule_index,
                    item_index + alt_index + 1,
                    item_follow,
                    choices,
                    named_token_slices,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                    expression_indices,
                ),
                first_name: format!("{choice_name}_ALT_{alt_index}_FIRST"),
                first: alt_first,
            });
        }
        choices.push(GeneratedChoice {
            name: choice_name.clone(),
            alternatives,
        });
        return format!("Item::Choice({choice_name})");
    }
    unreachable!("validated pattern item")
}

fn gen_ast(grammar: &Grammar) -> String {
    let token_sets = ast_token_sets(grammar);
    let mut out = String::from(header());
    out.push_str("use crate::{SyntaxNode, SyntaxToken};\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n\n",
        grammar.language.syntax_kind
    ));
    out.push_str("pub trait AstNode: Sized {\n");
    out.push_str("    fn can_cast(kind: SyntaxKind) -> bool;\n");
    out.push_str("    fn cast(node: SyntaxNode) -> Option<Self>;\n");
    out.push_str("    fn syntax(&self) -> &SyntaxNode;\n");
    out.push_str("}\n\n");

    for node in &grammar.ast.nodes {
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        out.push_str(&format!(
            "pub struct {} {{ syntax: SyntaxNode }}\n\n",
            node.name
        ));
        out.push_str(&format!("impl AstNode for {} {{\n", node.name));
        out.push_str(&format!(
            "    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{} }}\n",
            node.syntax
        ));
        out.push_str("    fn cast(node: SyntaxNode) -> Option<Self> {\n");
        out.push_str("        Self::can_cast(node.kind()).then_some(Self { syntax: node })\n");
        out.push_str("    }\n");
        out.push_str("    fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        out.push_str("}\n\n");
        out.push_str(&format!("impl {} {{\n", node.name));
        out.push_str("    pub fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        for accessor in &node.accessors {
            match accessor.kind.as_str() {
                "child" => {
                    let target = accessor.node.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<{}> {{ child(&self.syntax) }}\n",
                        accessor.name, target
                    ));
                }
                "children" => {
                    let target = accessor.node.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Vec<{}> {{ children(&self.syntax) }}\n",
                        accessor.name, target
                    ));
                }
                "first_token" => {
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<SyntaxToken> {{ self.syntax.first_token() }}\n",
                        accessor.name
                    ));
                }
                "token" => {
                    let token = accessor.token.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<SyntaxToken> {{ token(&self.syntax, SyntaxKind::{}) }}\n",
                        accessor.name, token
                    ));
                }
                "token_text" => {
                    let token = accessor.token.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<String> {{ token_text(&self.syntax, SyntaxKind::{}) }}\n",
                        accessor.name, token
                    ));
                }
                "first_token_text" => {
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<String> {{ self.syntax.first_token().map(|token| token.text().to_string()) }}\n",
                        accessor.name
                    ));
                }
                "tokens" => {
                    if let Some(token) = &accessor.token {
                        out.push_str(&format!(
                            "    pub fn {}(&self) -> Vec<SyntaxToken> {{ tokens(&self.syntax, SyntaxKind::{}) }}\n",
                            accessor.name, token
                        ));
                    } else {
                        let token_set = accessor.token_set.as_ref().expect("validated");
                        let predicate =
                            token_set_predicate(token_sets.get(token_set).expect("validated"));
                        out.push_str(&format!(
                            "    pub fn {}(&self) -> Vec<SyntaxToken> {{ tokens_matching(&self.syntax, |kind| {}) }}\n",
                            accessor.name, predicate
                        ));
                    }
                }
                "text_between" => {
                    let start = accessor.start.as_ref().expect("validated");
                    let end = accessor.end.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<String> {{ text_between(&self.syntax, SyntaxKind::{}, SyntaxKind::{}) }}\n",
                        accessor.name, start, end
                    ));
                }
                "enum" => {
                    let ast_enum = accessor.r#enum.as_ref().expect("validated");
                    if let Some(token) = &accessor.token {
                        out.push_str(&format!(
                            "    pub fn {}(&self) -> Option<{}> {{ token(&self.syntax, SyntaxKind::{}).and_then(|token| {}::from_token(token.kind())) }}\n",
                            accessor.name, ast_enum, token, ast_enum
                        ));
                    } else {
                        out.push_str(&format!(
                            "    pub fn {}(&self) -> Option<{}> {{ self.syntax.first_token().and_then(|token| {}::from_token(token.kind())) }}\n",
                            accessor.name, ast_enum, ast_enum
                        ));
                    }
                }
                "child_enum" => {
                    let ast_enum = accessor.r#enum.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<{}> {{ {}::from_node(&self.syntax) }}\n",
                        accessor.name, ast_enum, ast_enum
                    ));
                }
                _ => unreachable!("validated accessor kind"),
            }
        }
        out.push_str("}\n\n");
    }

    for ast_enum in &grammar.ast.enums {
        match ast_enum.kind.as_str() {
            "token" => {
                out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
                out.push_str(&format!("pub enum {} {{\n", ast_enum.name));
                for (variant, _) in &ast_enum.variants {
                    out.push_str(&format!("    {},\n", variant));
                }
                out.push_str("}\n\n");
                out.push_str(&format!("impl {} {{\n", ast_enum.name));
                out.push_str("    pub fn from_token(kind: SyntaxKind) -> Option<Self> {\n");
                out.push_str("        Some(match kind {\n");
                for (variant, token) in &ast_enum.variants {
                    out.push_str(&format!(
                        "            SyntaxKind::{} => Self::{},\n",
                        token, variant
                    ));
                }
                out.push_str("            _ => return None,\n");
                out.push_str("        })\n    }\n}\n\n");
            }
            "node" => {
                out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
                out.push_str(&format!("pub enum {} {{\n", ast_enum.name));
                for (variant, node) in &ast_enum.variants {
                    out.push_str(&format!("    {}({}),\n", variant, node));
                }
                out.push_str("}\n\n");
                out.push_str(&format!("impl {} {{\n", ast_enum.name));
                out.push_str("    pub fn from_node(node: &SyntaxNode) -> Option<Self> {\n");
                out.push_str("        for child in node.children() {\n");
                for (variant, ast_node) in &ast_enum.variants {
                    out.push_str(&format!(
                        "            if let Some(node) = {}::cast(child.clone()) {{ return Some(Self::{}(node)); }}\n",
                        ast_node, variant
                    ));
                }
                out.push_str("        }\n");
                out.push_str("        None\n");
                out.push_str("    }\n}\n\n");
            }
            _ => unreachable!("validated AST enum kind"),
        }
    }

    out.push_str("fn child<N: AstNode>(node: &SyntaxNode) -> Option<N> {\n");
    out.push_str("    node.children().find_map(N::cast)\n}\n\n");
    out.push_str("fn children<N: AstNode>(node: &SyntaxNode) -> Vec<N> {\n");
    out.push_str("    node.children().filter_map(N::cast).collect()\n}\n\n");
    out.push_str("fn token(node: &SyntaxNode, kind: SyntaxKind) -> Option<SyntaxToken> {\n");
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).find(|token| token.kind() == kind)\n}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("fn tokens(node: &SyntaxNode, kind: SyntaxKind) -> Vec<SyntaxToken> {\n");
    out.push_str("    tokens_matching(node, |token_kind| token_kind == kind)\n}\n\n");
    out.push_str("fn tokens_matching(node: &SyntaxNode, predicate: impl Fn(SyntaxKind) -> bool) -> Vec<SyntaxToken> {\n");
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).filter(|token| predicate(token.kind())).collect()\n}\n\n");
    out.push_str("fn token_text(node: &SyntaxNode, kind: SyntaxKind) -> Option<String> {\n");
    out.push_str("    token(node, kind).map(|token| token.text().to_string())\n}\n\n");
    out.push_str("fn text_between(node: &SyntaxNode, start: SyntaxKind, end: SyntaxKind) -> Option<String> {\n");
    out.push_str("    let mut seen_start = false;\n");
    out.push_str("    let mut text = String::new();\n");
    out.push_str("    for token in node.children_with_tokens().filter_map(|element| element.into_token()) {\n");
    out.push_str("        if token.kind() == start { seen_start = true; continue; }\n");
    out.push_str("        if token.kind() == end { return seen_start.then_some(text); }\n");
    out.push_str("        if seen_start { text.push_str(token.text()); }\n");
    out.push_str("    }\n");
    out.push_str("    None\n}\n");
    out
}

fn ast_token_sets(grammar: &Grammar) -> BTreeMap<String, BTreeSet<String>> {
    let all_tokens = grammar
        .token_names()
        .into_iter()
        .map(str::to_string)
        .collect::<BTreeSet<_>>();
    grammar
        .syntax
        .token_sets
        .iter()
        .map(|set| {
            let mut tokens = if set.include.as_deref() == Some("all_tokens") {
                all_tokens.clone()
            } else {
                set.tokens.iter().cloned().collect::<BTreeSet<_>>()
            };
            for token in &set.exclude {
                tokens.remove(token);
            }
            (set.name.clone(), tokens)
        })
        .collect()
}

fn token_set_predicate(tokens: &BTreeSet<String>) -> String {
    if tokens.is_empty() {
        return "false".to_string();
    }
    let tokens = tokens
        .iter()
        .map(|token| format!("SyntaxKind::{token}"))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("matches!(kind, {tokens})")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn toy_grammar(ast: &str) -> Grammar {
        ron::Options::default()
            .with_default_extension(ron::extensions::Extensions::IMPLICIT_SOME)
            .from_str(&format!(
                r#"(
                    language: (type_name: "ToyLanguage", syntax_kind: "ToyKind"),
                    diagnostics: (
                        invalid_token: "InvalidToken",
                        unexpected_token: "UnexpectedToken",
                        unexpected_eof: "UnexpectedEof",
                        kinds: [
                            (name: "InvalidToken", message: "invalid token"),
                            (name: "UnexpectedToken", message: "unexpected token"),
                            (name: "UnexpectedEof", message: "unexpected eof"),
                        ],
                    ),
                    tokens: (
                        rules: [
                            (name: "Whitespace", regex: "[ \n]+", trivia: skip),
                            (name: "LetKw", literal: "let"),
                            (name: "Ident", regex: "[A-Za-z_][A-Za-z0-9_]*"),
                            (name: "Int", regex: "[0-9]+"),
                            (name: "Semicolon", literal: ";"),
                        ],
                    ),
                    syntax: (
                        entry: "File",
                        nodes: ["File", "Stmt", "LetStmt", "Name"],
                        rules: [
                            (name: "File", pattern: [(repeat: "Stmt")]),
                            (name: "Stmt", pattern: [(choice: [(node: "LetStmt"), (node: "Name")])]),
                            (name: "LetStmt", pattern: [(token: "LetKw"), (repeat: "HeaderToken"), (token: "Semicolon")]),
                            (name: "Name", pattern: [(token: "Ident")]),
                        ],
                        token_sets: [
                            (name: "HeaderToken", tokens: ["Ident", "Int"]),
                        ],
                    ),
                    expressions: (items: []),
                    ast: {ast},
                )"#
            ))
            .unwrap()
    }

    #[test]
    fn generation_includes_pratt_expression_tables_for_non_dawn_grammar() {
        let grammar: Grammar = ron::Options::default()
            .with_default_extension(ron::extensions::Extensions::IMPLICIT_SOME)
            .from_str(
                r#"(
                    language: (type_name: "ToyLanguage", syntax_kind: "ToyKind"),
                    diagnostics: (
                        invalid_token: "InvalidToken",
                        unexpected_token: "UnexpectedToken",
                        unexpected_eof: "UnexpectedEof",
                        kinds: [
                            (name: "InvalidToken", message: "invalid token"),
                            (name: "UnexpectedToken", message: "unexpected token"),
                            (name: "UnexpectedEof", message: "unexpected eof"),
                        ],
                    ),
                    tokens: (
                        rules: [
                            (name: "Whitespace", regex: "[ \n]+", trivia: skip),
                            (name: "Int", regex: "[0-9]+"),
                            (name: "Plus", literal: "+"),
                        ],
                    ),
                    syntax: (
                        entry: "File",
                        nodes: ["File"],
                        rules: [(name: "File", pattern: [(expr: "Expr")])],
                        token_sets: [],
                    ),
                    expressions: (
                        items: [
                            (
                                name: "Expr",
                                root_node: "Expr",
                                atoms: [(token: "Int")],
                                infix: [(token: "Plus", node: "BinaryExpr", precedence: "Add", associativity: "left")],
                            ),
                        ],
                    ),
                    ast: (
                        root: "File",
                        nodes: [(name: "File", syntax: "File", accessors: [])],
                        enums: [],
                    ),
                )"#,
            )
            .unwrap();
        grammar.validate().unwrap();

        let parser = generate(&grammar)
            .into_iter()
            .find_map(|(path, text)| (path == "src/generated/parser.rs").then_some(text))
            .unwrap();
        assert!(parser.contains("Item::Expr(0)"));
        assert!(parser.contains("static EXPRESSIONS: &[Expression]"));
        assert!(parser.contains("InfixOp { token: SyntaxKind::Plus"));
    }

    #[test]
    fn generation_emits_rich_ast_accessors_and_node_enums() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [
                    (name: "File", syntax: "File", accessors: [(name: "statements", kind: "children", node: "Stmt")]),
                    (
                        name: "Stmt",
                        syntax: "Stmt",
                        accessors: [
                            (name: "let_stmt", kind: "child", node: "LetStmt"),
                            (name: "name", kind: "child", node: "Name"),
                            (name: "variant", kind: "child_enum", enum: "StmtKind"),
                        ],
                    ),
                    (
                        name: "LetStmt",
                        syntax: "LetStmt",
                        accessors: [
                            (name: "keyword", kind: "token", token: "LetKw"),
                            (name: "keyword_text", kind: "token_text", token: "LetKw"),
                            (name: "header_tokens", kind: "tokens", token_set: "HeaderToken"),
                            (name: "value", kind: "enum", enum: "LetValue", token: "LetKw"),
                        ],
                    ),
                    (
                        name: "Name",
                        syntax: "Name",
                        accessors: [
                            (name: "text", kind: "token_text", token: "Ident"),
                            (name: "first_text", kind: "first_token_text"),
                            (name: "idents", kind: "tokens", token: "Ident"),
                        ],
                    ),
                ],
                enums: [
                    (name: "LetValue", from_node: "LetStmt", variants: [("Let", "LetKw")]),
                    (
                        name: "StmtKind",
                        kind: "node",
                        from_node: "Stmt",
                        variants: [("LetStmt", "LetStmt"), ("Name", "Name")],
                    ),
                ],
            )"#,
        );
        grammar.validate().unwrap();

        let ast = generate(&grammar)
            .into_iter()
            .find_map(|(path, text)| (path == "src/generated/ast.rs").then_some(text))
            .unwrap();
        assert!(ast.contains("pub fn keyword_text(&self) -> Option<String>"));
        assert!(ast.contains("pub fn header_tokens(&self) -> Vec<SyntaxToken>"));
        assert!(ast.contains("pub fn value(&self) -> Option<LetValue>"));
        assert!(ast.contains("pub enum StmtKind"));
        assert!(ast.contains("LetStmt(LetStmt)"));
        assert!(ast.contains("pub fn variant(&self) -> Option<StmtKind>"));
        assert!(ast.contains("pub fn from_token(kind: SyntaxKind) -> Option<Self>"));
    }

    #[test]
    fn validation_rejects_invalid_accessor_kind() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [
                    (name: "File", syntax: "File", accessors: [(name: "bad", kind: "missing")]),
                    (name: "Stmt", syntax: "Stmt", accessors: []),
                    (name: "LetStmt", syntax: "LetStmt", accessors: []),
                    (name: "Name", syntax: "Name", accessors: []),
                ],
                enums: [],
            )"#,
        );

        let error = grammar.validate().unwrap_err().to_string();
        assert!(error.contains("invalid kind 'missing'"));
    }

    #[test]
    fn validation_rejects_invalid_accessor_fields() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [
                    (name: "File", syntax: "File", accessors: [(name: "bad", kind: "token_text")]),
                    (name: "Stmt", syntax: "Stmt", accessors: []),
                    (name: "LetStmt", syntax: "LetStmt", accessors: []),
                    (name: "Name", syntax: "Name", accessors: []),
                ],
                enums: [],
            )"#,
        );

        let error = grammar.validate().unwrap_err().to_string();
        assert!(error.contains("missing token"));
    }

    #[test]
    fn validation_rejects_token_set_and_token_together() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [
                    (
                        name: "File",
                        syntax: "File",
                        accessors: [(name: "bad", kind: "tokens", token: "Ident", token_set: "HeaderToken")],
                    ),
                    (name: "Stmt", syntax: "Stmt", accessors: []),
                    (name: "LetStmt", syntax: "LetStmt", accessors: []),
                    (name: "Name", syntax: "Name", accessors: []),
                ],
                enums: [],
            )"#,
        );

        let error = grammar.validate().unwrap_err().to_string();
        assert!(error.contains("exactly one of token or token_set"));
    }

    #[test]
    fn validation_rejects_mismatched_enum_accessor() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [
                    (name: "File", syntax: "File", accessors: [(name: "bad", kind: "enum", enum: "LetValue")]),
                    (name: "Stmt", syntax: "Stmt", accessors: []),
                    (name: "LetStmt", syntax: "LetStmt", accessors: []),
                    (name: "Name", syntax: "Name", accessors: []),
                ],
                enums: [(name: "LetValue", from_node: "LetStmt", variants: [("Let", "LetKw")])],
            )"#,
        );

        let error = grammar.validate().unwrap_err().to_string();
        assert!(error.contains("expected 'File'"));
    }
}
