use std::collections::{BTreeMap, BTreeSet, HashMap};
use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use clap::Parser;
use ron::extensions::Extensions;
use serde::Deserialize;

mod semantics;
mod spec;

use semantics::SemanticsSpec;
use spec::{Grammar, PatternItem, TriviaPolicy};

#[derive(Debug, Parser)]
struct Args {
    #[arg(long, conflicts_with = "check")]
    write: bool,
    #[arg(long, conflicts_with = "write")]
    check: bool,
    #[arg(long)]
    grammar: PathBuf,
    #[arg(long)]
    semantics: Option<PathBuf>,
    #[arg(long)]
    builtins: Option<PathBuf>,
    #[arg(long)]
    out: PathBuf,
    #[arg(long)]
    monarch_out: Option<PathBuf>,
}

fn main() -> Result<()> {
    let args = Args::parse();
    if !args.write && !args.check {
        bail!("pass --write or --check");
    }

    let grammar = Grammar::load(&args.grammar)?;
    grammar.validate()?;
    let mut files = if let Some(path) = &args.semantics {
        let semantics = SemanticsSpec::load(path)?;
        semantics.validate(&grammar)?;
        generate_semantics(&grammar, &semantics)
    } else {
        generate(&grammar)
    };
    let monarch_file = if let Some(path) = &args.monarch_out {
        let builtins = args
            .builtins
            .as_deref()
            .map(BuiltinsSpec::load)
            .transpose()?;
        Some((path.clone(), gen_monarch(&grammar, builtins.as_ref())))
    } else {
        None
    };

    if args.write {
        fs::create_dir_all(&args.out)?;
        for (name, contents) in files.drain(..) {
            let path = args.out.join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)?;
        }
        if let Some((path, contents)) = monarch_file {
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)?;
        }
        return Ok(());
    }

    let mut stale = Vec::new();
    for (name, expected) in files {
        let path = args.out.join(name);
        let actual = fs::read_to_string(&path)
            .with_context(|| format!("failed to read generated file {}", path.display()))?;
        if actual != expected {
            stale.push(name.to_string());
        }
    }
    if let Some((path, expected)) = monarch_file {
        let actual = fs::read_to_string(&path)
            .with_context(|| format!("failed to read generated file {}", path.display()))?;
        if actual != expected {
            stale.push(path.display().to_string());
        }
    }

    if !stale.is_empty() {
        bail!("generated files are stale: {}", stale.join(", "));
    }
    Ok(())
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BuiltinsSpec {
    version: u32,
    primitives: Vec<String>,
    documents: Vec<BuiltinDocument>,
    records: Vec<BuiltinRecord>,
}

impl BuiltinsSpec {
    fn load(path: &std::path::Path) -> Result<Self> {
        let text = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        let spec: Self = ron::Options::default()
            .with_default_extension(Extensions::IMPLICIT_SOME)
            .from_str(&text)
            .with_context(|| format!("failed to parse {}", path.display()))?;
        if spec.version != 1 {
            bail!("builtins spec version must be 1");
        }
        Ok(spec)
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BuiltinDocument {
    name: String,
    fields: Vec<BuiltinField>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BuiltinRecord {
    name: String,
    fields: Vec<BuiltinField>,
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct BuiltinField {
    name: String,
    ty: String,
    cardinality: String,
}

pub fn generate_semantics(
    grammar: &Grammar,
    semantics: &SemanticsSpec,
) -> Vec<(&'static str, String)> {
    semantics::generate(grammar, semantics, header())
}

pub fn generate(grammar: &Grammar) -> Vec<(&'static str, String)> {
    vec![
        ("src/generated/mod.rs", gen_mod()),
        ("src/generated/diagnostic.rs", gen_diagnostic(grammar)),
        ("src/generated/kind.rs", gen_kind(grammar)),
        ("src/generated/lexer.rs", gen_lexer(grammar)),
        ("src/generated/parser.rs", gen_parser(grammar)),
        ("src/generated/ast.rs", gen_ast(grammar)),
    ]
}

fn header() -> &'static str {
    "// @generated by syntax-gen. Do not edit by hand.\n\n"
}

fn gen_mod() -> String {
    let mut out = String::from(header());
    out.push_str("pub mod ast;\n");
    out.push_str("pub mod diagnostic;\n");
    out.push_str("pub mod kind;\n");
    out.push_str("pub mod lexer;\n");
    out.push_str("pub mod parser;\n");
    out
}

fn gen_monarch(grammar: &Grammar, builtins: Option<&BuiltinsSpec>) -> String {
    let mut keywords = BTreeSet::new();
    let mut operators = BTreeSet::new();
    for token in &grammar.tokens.rules {
        if let Some(literal) = &token.literal {
            if token.name.ends_with("Kw") {
                keywords.insert(literal.clone());
            } else if literal.chars().all(|ch| !ch.is_alphanumeric() && ch != '_') {
                operators.insert(literal.clone());
            }
        }
    }

    let mut vocabulary = BTreeSet::new();
    let mut types = BTreeSet::new();
    if let Some(builtins) = builtins {
        for primitive in &builtins.primitives {
            types.insert(primitive.clone());
        }
        for document in &builtins.documents {
            vocabulary.insert(document.name.clone());
            for field in &document.fields {
                vocabulary.insert(field.name.clone());
                collect_type_names(&field.ty, &mut types);
                let _ = &field.cardinality;
            }
        }
        for record in &builtins.records {
            types.insert(record.name.clone());
            for field in &record.fields {
                vocabulary.insert(field.name.clone());
                collect_type_names(&field.ty, &mut types);
                let _ = &field.cardinality;
            }
        }
    }

    let mut out = String::from(header());
    out.push_str("import type { languages } from \"monaco-editor\";\n\n");
    out.push_str("export const dawnMonarch: languages.IMonarchLanguage = {\n");
    emit_ts_array(&mut out, "keywords", keywords.iter());
    emit_ts_array(&mut out, "operators", operators.iter());
    emit_ts_array(&mut out, "dawnVocabulary", vocabulary.iter());
    emit_ts_array(&mut out, "types", types.iter());
    out.push_str("  tokenizer: {\n");
    out.push_str("    root: [\n");
    out.push_str("      [/\\/\\/.*$/, \"comment\"],\n");
    out.push_str("      [/\\/\\*/, \"comment\", \"@comment\"],\n");
    out.push_str("      [/<[^>]*>/, \"string\"],\n");
    out.push_str("      [/\"([^\"\\\\]|\\\\.)*$/, \"string.invalid\"],\n");
    out.push_str("      [/\"/, \"string\", \"@string\"],\n");
    out.push_str("      [/#[0-9A-Fa-f]{3}([0-9A-Fa-f]{3})?/, \"number.hex\"],\n");
    out.push_str("      [/([0-9][0-9_]*(\\.[0-9_]+)?|\\.[0-9][0-9_]*)[a-zA-Z]+/, \"number\"],\n");
    out.push_str("      [/(([0-9][0-9_]*\\.[0-9][0-9_]*|\\.[0-9][0-9_]*)([eE][+-]?[0-9][0-9_]*)?|[0-9][0-9_]*[eE][+-]?[0-9][0-9_]*)/, \"number.float\"],\n");
    out.push_str("      [/[0-9][0-9_]*/, \"number\"],\n");
    out.push_str("      [/[A-Za-z_][A-Za-z0-9_]*/, { cases: { \"@keywords\": \"keyword\", \"@types\": \"type\", \"@dawnVocabulary\": \"identifier.predefined\", \"@default\": \"identifier\" } }],\n");
    out.push_str("      [/[{}\\[\\]()]/, \"delimiter.bracket\"],\n");
    out.push_str("      [/[;,.]/, \"delimiter\"],\n");
    out.push_str("      [/[=!<>?:&|+\\-*\\/%^]+/, { cases: { \"@operators\": \"operator\", \"@default\": \"operator\" } }]\n");
    out.push_str("    ],\n");
    out.push_str("    comment: [[/[^/*]+/, \"comment\"], [/\\*\\//, \"comment\", \"@pop\"], [/[/*]/, \"comment\"]],\n");
    out.push_str("    string: [[/[^\"\\\\]+/, \"string\"], [/\\\\./, \"string.escape\"], [/\"/, \"string\", \"@pop\"]]\n");
    out.push_str("  }\n");
    out.push_str("};\n");
    out
}

fn collect_type_names(ty: &str, output: &mut BTreeSet<String>) {
    let mut current = String::new();
    for ch in ty.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            current.push(ch);
        } else if !current.is_empty() {
            output.insert(std::mem::take(&mut current));
        }
    }
    if !current.is_empty() {
        output.insert(current);
    }
}

fn emit_ts_array<'a>(out: &mut String, name: &str, values: impl Iterator<Item = &'a String>) {
    out.push_str(&format!("  {name}: ["));
    let mut first = true;
    for value in values {
        if !first {
            out.push_str(", ");
        }
        first = false;
        out.push_str(&format!("{value:?}"));
    }
    out.push_str("],\n");
}

fn gen_diagnostic(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum DiagnosticKind {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!("    {},\n", diagnostic.name));
    }
    out.push_str("}\n\n");
    out.push_str(&format!(
        "pub const INVALID_TOKEN_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n",
        grammar.diagnostics.invalid_token
    ));
    out.push_str(&format!(
        "pub const UNEXPECTED_TOKEN_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n",
        grammar.diagnostics.unexpected_token
    ));
    out.push_str(&format!(
        "pub const UNEXPECTED_EOF_DIAGNOSTIC: DiagnosticKind = DiagnosticKind::{};\n\n",
        grammar.diagnostics.unexpected_eof
    ));
    out.push_str("impl DiagnosticKind {\n");
    out.push_str("    pub fn message(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!(
            "            Self::{} => {:?},\n",
            diagnostic.name, diagnostic.message
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::fmt::Display for DiagnosticKind {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        f.write_str(self.message())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for DiagnosticKind {}\n");
    out
}

fn gen_kind(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    let syntax_kind = &grammar.language.syntax_kind;
    let language_type = &grammar.language.type_name;
    out.push_str(&format!("#[repr(u16)]\npub enum {syntax_kind} {{\n"));
    for name in grammar.syntax_kinds() {
        out.push_str("    ");
        out.push_str(name);
        out.push_str(",\n");
    }
    out.push_str("    Error,\n}\n\n");
    out.push_str(&format!("impl {syntax_kind} {{\n"));
    out.push_str("    pub fn is_trivia(self) -> bool {\n");
    let trivia = grammar
        .trivia_names()
        .into_iter()
        .map(|trivia| format!("Self::{trivia}"))
        .collect::<Vec<_>>();
    if trivia.is_empty() {
        out.push_str("        false\n");
    } else {
        out.push_str("        matches!(self, ");
        out.push_str(&trivia.join(" | "));
        out.push_str(")\n");
    }
    out.push_str("    }\n}\n\n");
    out.push_str(&format!(
        "impl From<{syntax_kind}> for rowan::SyntaxKind {{\n"
    ));
    out.push_str(&format!("    fn from(kind: {syntax_kind}) -> Self {{\n"));
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str(&format!("pub enum {language_type} {{}}\n\n"));
    out.push_str(&format!("impl rowan::Language for {language_type} {{\n"));
    out.push_str(&format!("    type Kind = {syntax_kind};\n\n"));
    out.push_str("    fn kind_from_raw(raw: rowan::SyntaxKind) -> Self::Kind {\n");
    out.push_str(&format!(
        "        assert!(raw.0 <= {syntax_kind}::Error as u16);\n"
    ));
    out.push_str(&format!(
        "        unsafe {{ std::mem::transmute::<u16, {syntax_kind}>(raw.0) }}\n"
    ));
    out.push_str("    }\n\n");
    out.push_str("    fn kind_to_raw(kind: Self::Kind) -> rowan::SyntaxKind {\n");
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n}\n");
    out
}

fn gen_lexer(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("use std::sync::OnceLock;\n\n");
    out.push_str("use regex::Regex;\n\n");
    out.push_str("use crate::diagnostic::{Diagnostic, DiagnosticKind};\n");
    out.push_str("use crate::generated::diagnostic::INVALID_TOKEN_DIAGNOSTIC;\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n\n",
        grammar.language.syntax_kind
    ));
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub struct LexToken {\n");
    out.push_str("    pub kind: SyntaxKind,\n");
    out.push_str("    pub range: std::ops::Range<usize>,\n");
    out.push_str("    pub text: String,\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("enum Matcher {\n");
    out.push_str("    Regex(usize),\n");
    out.push_str("    Delimited { start: &'static str, end: &'static str },\n");
    out.push_str("    Literal(&'static str),\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy)]\n");
    out.push_str("struct Rule {\n");
    out.push_str("    kind: SyntaxKind,\n");
    out.push_str("    matcher: Matcher,\n");
    out.push_str("    skip: bool,\n");
    out.push_str("    diagnostic: Option<DiagnosticKind>,\n");
    out.push_str("}\n\n");

    let mut regexes = Vec::new();
    let mut rules = Vec::new();
    for token in &grammar.tokens.rules {
        let matcher = if let Some(pattern) = &token.regex {
            let index = regexes.len();
            regexes.push(pattern.clone());
            format!("Matcher::Regex({index})")
        } else if let Some(literal) = &token.literal {
            format!("Matcher::Literal({literal:?})")
        } else {
            format!(
                "Matcher::Delimited {{ start: {:?}, end: {:?} }}",
                token.start.as_ref().expect("validated"),
                token.end.as_ref().expect("validated")
            )
        };
        rules.push(format!(
            "    Rule {{ kind: SyntaxKind::{}, matcher: {}, skip: {}, diagnostic: {} }},\n",
            token.name,
            matcher,
            matches!(token.trivia, TriviaPolicy::Skip),
            diagnostic_option(token.diagnostic.as_deref())
        ));
    }

    out.push_str("const REGEX_PATTERNS: &[&str] = &[\n");
    for pattern in regexes {
        out.push_str(&format!("    {:?},\n", format!("^(?:{pattern})")));
    }
    out.push_str("];\n\n");
    out.push_str("const RULES: &[Rule] = &[\n");
    for rule in rules {
        out.push_str(&rule);
    }
    out.push_str("];\n\n");
    out.push_str(include_str!("templates/lexer.rs"));
    out
}

fn diagnostic_option(name: Option<&str>) -> String {
    name.map(|name| format!("Some(DiagnosticKind::{name})"))
        .unwrap_or_else(|| "None".to_string())
}

fn gen_parser(grammar: &Grammar) -> String {
    let grammar_sets = GrammarSets::new(grammar);
    let mut out = String::from(header());
    out.push_str("use rowan::{GreenNode, GreenNodeBuilder};\n\n");
    out.push_str("use crate::diagnostic::Diagnostic;\n");
    out.push_str("use crate::generated::diagnostic::{UNEXPECTED_EOF_DIAGNOSTIC, UNEXPECTED_TOKEN_DIAGNOSTIC};\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n",
        grammar.language.syntax_kind
    ));
    out.push_str("use crate::generated::lexer::LexToken;\n\n");

    for (name, tokens) in &grammar_sets.named_token_slices {
        emit_token_slice(&mut out, name, tokens);
    }
    out.push_str("fn token_set(index: usize) -> &'static [SyntaxKind] {\n");
    out.push_str("    match index {\n");
    for index in 0..grammar.syntax.token_sets.len() {
        out.push_str(&format!("        {index} => TOKEN_SET_{index},\n"));
    }
    out.push_str("        _ => unreachable!(\"generated parser requested invalid token set\"),\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");

    for choice in &grammar_sets.choices {
        for alt in &choice.alternatives {
            emit_token_slice(&mut out, &alt.first_name, &alt.first);
        }
        out.push_str(&format!("static {}: &[Alternative] = &[\n", choice.name));
        for alt in &choice.alternatives {
            out.push_str(&format!(
                "    Alternative {{ item: {}, first: {} }},\n",
                alt.item_expr, alt.first_name
            ));
        }
        out.push_str("];\n\n");
    }

    for sequence in &grammar_sets.sequences {
        emit_token_slice(&mut out, &sequence.first_name, &sequence.first);
        out.push_str(&format!("static {}: &[Item] = &[\n", sequence.name));
        for item in &sequence.items {
            out.push_str(&format!("    {},\n", item));
        }
        out.push_str("];\n\n");
    }

    for rule in &grammar_sets.rules {
        emit_token_slice(&mut out, &rule.first_name, &rule.first);
        out.push_str(&format!("static {}: &[Item] = &[\n", rule.items_name));
        for item in &rule.items {
            out.push_str(&format!("    {},\n", item));
        }
        out.push_str("];\n\n");
    }

    out.push_str("const ENTRY_RULE: usize = ");
    out.push_str(&grammar_sets.entry_rule.to_string());
    out.push_str(";\n\n");
    out.push_str("static RULES: &[Rule] = &[\n");
    for rule in &grammar_sets.rules {
        out.push_str(&format!(
            "    Rule {{ kind: SyntaxKind::{}, items: {}, first: {} }},\n",
            rule.kind, rule.items_name, rule.first_name
        ));
    }
    out.push_str("];\n\n");

    emit_expression_tables(&mut out, grammar, &grammar_sets);

    out.push_str(include_str!("templates/parser.rs"));
    out
}

fn emit_expression_tables(out: &mut String, grammar: &Grammar, grammar_sets: &GrammarSets) {
    out.push_str("const PREFIX_BINDING_POWER: u8 = 200;\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct Expression { root: SyntaxKind, atoms: &'static [ExprAtom], prefix: &'static [PrefixOp], infix: &'static [InfixOp], postfix: &'static [PostfixOp] }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct ExprAtom { item: Item, first: &'static [SyntaxKind] }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct PrefixOp { token: SyntaxKind, node: SyntaxKind }\n\n");
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str(
        "struct InfixOp { token: SyntaxKind, node: SyntaxKind, left_bp: u8, right_bp: u8 }\n\n",
    );
    out.push_str("#[derive(Clone, Copy)]\n");
    out.push_str("struct PostfixOp { node: SyntaxKind, items: &'static [Item], first: &'static [SyntaxKind] }\n\n");

    for (expr_index, expression) in grammar.expressions.items.iter().enumerate() {
        for (atom_index, atom) in expression.atoms.iter().enumerate() {
            let first = if let Some(token) = &atom.token {
                BTreeSet::from([token.clone()])
            } else {
                let node = atom.node.as_ref().expect("validated");
                grammar_sets.rule_first(node).clone()
            };
            emit_token_slice(
                out,
                &format!("EXPR_{expr_index}_ATOM_{atom_index}_FIRST"),
                &first,
            );
        }
        for (postfix_index, postfix) in expression.postfix.iter().enumerate() {
            let first = first_of_sequence(
                &postfix.pattern,
                &grammar_sets.first,
                &grammar_sets.nullable_rules,
                &grammar_sets.rule_indices,
                &grammar_sets.token_sets,
                &grammar_sets.token_set_indices,
                &grammar_sets.expression_indices,
                &grammar_sets.expression_first,
            );
            emit_token_slice(
                out,
                &format!("EXPR_{expr_index}_POSTFIX_{postfix_index}_FIRST"),
                &first,
            );
            out.push_str(&format!(
                "static EXPR_{expr_index}_POSTFIX_{postfix_index}_ITEMS: &[Item] = &[\n"
            ));
            let parent_follow = BTreeSet::new();
            let mut repeat_stops = BTreeMap::new();
            for (item_index, item) in postfix.pattern.iter().enumerate() {
                let stop = item_follow_at(
                    &postfix.pattern,
                    item_index,
                    &parent_follow,
                    &grammar_sets.first,
                    &grammar_sets.nullable_rules,
                    &grammar_sets.rule_indices,
                    &grammar_sets.token_sets,
                    &grammar_sets.token_set_indices,
                    &grammar_sets.expression_indices,
                    &grammar_sets.expression_first,
                );
                let mut postfix_choices = Vec::new();
                let mut postfix_sequences = Vec::new();
                let expr = item_expr(
                    item,
                    usize::MAX - expr_index,
                    item_index,
                    &stop,
                    &mut postfix_choices,
                    &mut postfix_sequences,
                    &mut repeat_stops,
                    &grammar_sets.first,
                    &grammar_sets.nullable_rules,
                    &grammar_sets.rule_indices,
                    &grammar_sets.token_sets,
                    &grammar_sets.token_set_indices,
                    &grammar_sets.expression_indices,
                    &grammar_sets.expression_first,
                );
                out.push_str(&format!("    {expr},\n"));
            }
            out.push_str("];\n\n");
            for (name, tokens) in repeat_stops {
                emit_token_slice(out, &name, &tokens);
            }
        }

        out.push_str(&format!(
            "static EXPR_{expr_index}_ATOMS: &[ExprAtom] = &[\n"
        ));
        for (atom_index, atom) in expression.atoms.iter().enumerate() {
            let item = if let Some(token) = &atom.token {
                format!("Item::Token(SyntaxKind::{token})")
            } else {
                let node = atom.node.as_ref().expect("validated");
                format!(
                    "Item::Node({})",
                    grammar_sets.rule_indices.get(node).expect("validated")
                )
            };
            out.push_str(&format!(
                "    ExprAtom {{ item: {item}, first: EXPR_{expr_index}_ATOM_{atom_index}_FIRST }},\n"
            ));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "static EXPR_{expr_index}_PREFIX: &[PrefixOp] = &[\n"
        ));
        for prefix in &expression.prefix {
            out.push_str(&format!(
                "    PrefixOp {{ token: SyntaxKind::{}, node: SyntaxKind::{} }},\n",
                prefix.token, prefix.node
            ));
        }
        out.push_str("];\n\n");

        let mut precedence = BTreeMap::<String, u8>::new();
        for infix in &expression.infix {
            if !precedence.contains_key(&infix.precedence) {
                let bp = ((precedence.len() + 1) * 10) as u8;
                precedence.insert(infix.precedence.clone(), bp);
            }
        }
        out.push_str(&format!(
            "static EXPR_{expr_index}_INFIX: &[InfixOp] = &[\n"
        ));
        for infix in &expression.infix {
            let bp = precedence[&infix.precedence];
            let (left_bp, right_bp) = if infix.associativity == "right" {
                (bp, bp)
            } else {
                (bp, bp + 1)
            };
            out.push_str(&format!(
                "    InfixOp {{ token: SyntaxKind::{}, node: SyntaxKind::{}, left_bp: {left_bp}, right_bp: {right_bp} }},\n",
                infix.token, infix.node
            ));
        }
        out.push_str("];\n\n");

        out.push_str(&format!(
            "static EXPR_{expr_index}_POSTFIX: &[PostfixOp] = &[\n"
        ));
        for (postfix_index, postfix) in expression.postfix.iter().enumerate() {
            out.push_str(&format!(
                "    PostfixOp {{ node: SyntaxKind::{}, items: EXPR_{expr_index}_POSTFIX_{postfix_index}_ITEMS, first: EXPR_{expr_index}_POSTFIX_{postfix_index}_FIRST }},\n",
                postfix.node
            ));
        }
        out.push_str("];\n\n");
    }

    out.push_str("static EXPRESSIONS: &[Expression] = &[\n");
    for (expr_index, expression) in grammar.expressions.items.iter().enumerate() {
        out.push_str(&format!(
            "    Expression {{ root: SyntaxKind::{}, atoms: EXPR_{expr_index}_ATOMS, prefix: EXPR_{expr_index}_PREFIX, infix: EXPR_{expr_index}_INFIX, postfix: EXPR_{expr_index}_POSTFIX }},\n",
            expression.root_node
        ));
    }
    out.push_str("];\n\n");
}

fn emit_token_slice(out: &mut String, name: &str, tokens: &BTreeSet<String>) {
    out.push_str(&format!("static {name}: &[SyntaxKind] = &[\n"));
    for token in tokens {
        out.push_str(&format!("    SyntaxKind::{token},\n"));
    }
    out.push_str("];\n\n");
}

struct GrammarSets {
    entry_rule: usize,
    rules: Vec<GeneratedRule>,
    choices: Vec<GeneratedChoice>,
    sequences: Vec<GeneratedSequence>,
    named_token_slices: BTreeMap<String, BTreeSet<String>>,
    rule_indices: HashMap<String, usize>,
    token_set_indices: HashMap<String, usize>,
    token_sets: Vec<BTreeSet<String>>,
    first: Vec<BTreeSet<String>>,
    nullable_rules: Vec<bool>,
    expression_indices: HashMap<String, usize>,
    expression_first: Vec<BTreeSet<String>>,
}

struct GeneratedRule {
    kind: String,
    items_name: String,
    first_name: String,
    items: Vec<String>,
    first: BTreeSet<String>,
}

struct GeneratedChoice {
    name: String,
    alternatives: Vec<GeneratedAlternative>,
}

struct GeneratedSequence {
    name: String,
    first_name: String,
    items: Vec<String>,
    first: BTreeSet<String>,
}

struct GeneratedAlternative {
    item_expr: String,
    first_name: String,
    first: BTreeSet<String>,
}

impl GrammarSets {
    fn new(grammar: &Grammar) -> Self {
        let rule_indices = grammar
            .syntax
            .rules
            .iter()
            .enumerate()
            .map(|(index, rule)| (rule.name.clone(), index))
            .collect::<HashMap<_, _>>();
        let token_set_indices = grammar
            .syntax
            .token_sets
            .iter()
            .enumerate()
            .map(|(index, set)| (set.name.clone(), index))
            .collect::<HashMap<_, _>>();
        let all_tokens = grammar
            .token_names()
            .into_iter()
            .map(str::to_string)
            .collect::<BTreeSet<_>>();
        let token_sets = grammar
            .syntax
            .token_sets
            .iter()
            .map(|set| {
                let mut tokens = if set.include.as_deref() == Some("all_tokens") {
                    all_tokens.clone()
                } else {
                    set.tokens.iter().cloned().collect::<BTreeSet<_>>()
                };
                for token in &set.exclude {
                    tokens.remove(token);
                }
                tokens
            })
            .collect::<Vec<_>>();
        let expression_indices = grammar
            .expressions
            .items
            .iter()
            .enumerate()
            .map(|(index, expression)| (expression.name.clone(), index))
            .collect::<HashMap<_, _>>();
        let mut expression_first = grammar
            .expressions
            .items
            .iter()
            .map(|expression| expression_first_set(expression, &first_placeholder(&rule_indices)))
            .collect::<Vec<_>>();

        let mut nullable_rules = vec![false; grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            for (index, rule) in grammar.syntax.rules.iter().enumerate() {
                if !nullable_rules[index]
                    && pattern_nullable_with(
                        &rule.pattern,
                        &nullable_rules,
                        &rule_indices,
                        &token_set_indices,
                        &expression_indices,
                        &expression_first,
                    )
                {
                    nullable_rules[index] = true;
                    changed = true;
                }
            }
            if !changed {
                break;
            }
        }

        let mut first = vec![BTreeSet::new(); grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            expression_first = grammar
                .expressions
                .items
                .iter()
                .map(|expression| {
                    expression_first_set(expression, &first_by_name(&rule_indices, &first))
                })
                .collect::<Vec<_>>();
            for (index, rule) in grammar.syntax.rules.iter().enumerate() {
                let item_first = first_of_sequence(
                    &rule.pattern,
                    &first,
                    &nullable_rules,
                    &rule_indices,
                    &token_sets,
                    &token_set_indices,
                    &expression_indices,
                    &expression_first,
                );
                changed |= extend_set(&mut first[index], item_first);
            }
            if !changed {
                break;
            }
        }

        let mut follow = vec![BTreeSet::new(); grammar.syntax.rules.len()];
        loop {
            let mut changed = false;
            for (rule_index, rule) in grammar.syntax.rules.iter().enumerate() {
                changed |= collect_follow(
                    &rule.pattern,
                    &follow[rule_index].clone(),
                    &mut follow,
                    &first,
                    &nullable_rules,
                    &rule_indices,
                    &token_sets,
                    &token_set_indices,
                    &expression_indices,
                    &expression_first,
                );
            }
            if !changed {
                break;
            }
        }

        let mut choices = Vec::new();
        let mut sequences = Vec::new();
        let mut named_token_slices = BTreeMap::new();
        for (index, set) in grammar.syntax.token_sets.iter().enumerate() {
            named_token_slices.insert(format!("TOKEN_SET_{index}"), token_sets[index].clone());
            let _ = set;
        }

        let mut generated_rules = Vec::new();
        for (rule_index, rule) in grammar.syntax.rules.iter().enumerate() {
            let items = rule
                .pattern
                .iter()
                .enumerate()
                .map(|(item_index, item)| {
                    let stop = item_follow_at(
                        &rule.pattern,
                        item_index,
                        &follow[rule_index],
                        &first,
                        &nullable_rules,
                        &rule_indices,
                        &token_sets,
                        &token_set_indices,
                        &expression_indices,
                        &expression_first,
                    );
                    item_expr(
                        item,
                        rule_index,
                        item_index,
                        &stop,
                        &mut choices,
                        &mut sequences,
                        &mut named_token_slices,
                        &first,
                        &nullable_rules,
                        &rule_indices,
                        &token_sets,
                        &token_set_indices,
                        &expression_indices,
                        &expression_first,
                    )
                })
                .collect::<Vec<_>>();
            generated_rules.push(GeneratedRule {
                kind: rule.name.clone(),
                items_name: format!("RULE_{rule_index}_ITEMS"),
                first_name: format!("RULE_{rule_index}_FIRST"),
                items,
                first: first[rule_index].clone(),
            });
        }

        Self {
            entry_rule: *rule_indices.get(&grammar.syntax.entry).expect("validated"),
            rules: generated_rules,
            choices,
            sequences,
            named_token_slices,
            rule_indices,
            token_set_indices,
            token_sets,
            first,
            nullable_rules,
            expression_indices,
            expression_first,
        }
    }

    fn rule_first(&self, name: &str) -> &BTreeSet<String> {
        &self.first[*self.rule_indices.get(name).expect("validated")]
    }
}

fn extend_set(target: &mut BTreeSet<String>, source: BTreeSet<String>) -> bool {
    let before = target.len();
    target.extend(source);
    target.len() != before
}

fn first_placeholder(rule_indices: &HashMap<String, usize>) -> HashMap<String, BTreeSet<String>> {
    rule_indices
        .keys()
        .map(|name| (name.clone(), BTreeSet::new()))
        .collect()
}

fn first_by_name(
    rule_indices: &HashMap<String, usize>,
    first: &[BTreeSet<String>],
) -> HashMap<String, BTreeSet<String>> {
    rule_indices
        .iter()
        .map(|(name, index)| (name.clone(), first[*index].clone()))
        .collect()
}

fn expression_first_set(
    expression: &spec::ExpressionSpec,
    rule_first: &HashMap<String, BTreeSet<String>>,
) -> BTreeSet<String> {
    let mut result = expression
        .prefix
        .iter()
        .map(|prefix| prefix.token.clone())
        .collect::<BTreeSet<_>>();
    for atom in &expression.atoms {
        if let Some(token) = &atom.token {
            result.insert(token.clone());
        }
        if let Some(node) = &atom.node {
            if let Some(first) = rule_first.get(node) {
                result.extend(first.iter().cloned());
            }
        }
    }
    result
}

fn first_of_sequence(
    items: &[PatternItem],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> BTreeSet<String> {
    let mut result = BTreeSet::new();
    for item in items {
        result.extend(first_of_item(
            item,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        ));
        if !item_nullable_with(
            item,
            nullable_rules,
            rule_indices,
            token_set_indices,
            expression_indices,
            expression_first,
        ) {
            break;
        }
    }
    result
}

fn first_of_item(
    item: &PatternItem,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> BTreeSet<String> {
    if let Some(token) = &item.token {
        return BTreeSet::from([token.clone()]);
    }
    if let Some(node) = &item.node {
        return first[*rule_indices.get(node).expect("validated")].clone();
    }
    if let Some(repeat) = &item.repeat {
        return first_of_sequence(
            repeat,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
    }
    if let Some(optional) = &item.optional {
        return first_of_sequence(
            optional,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
    }
    if let Some(choice) = &item.choice {
        return choice
            .iter()
            .flat_map(|alt| {
                first_of_item(
                    alt,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                    expression_indices,
                    expression_first,
                )
            })
            .collect();
    }
    if let Some(token_set) = &item.token_set {
        return token_sets[*token_set_indices.get(token_set).expect("validated")].clone();
    }
    if let Some(expr) = &item.expr {
        return expression_first[*expression_indices.get(expr).expect("validated")].clone();
    }
    BTreeSet::new()
}

fn pattern_nullable_with(
    pattern: &[PatternItem],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> bool {
    pattern.iter().all(|item| {
        item_nullable_with(
            item,
            nullable_rules,
            rule_indices,
            token_set_indices,
            expression_indices,
            expression_first,
        )
    })
}

fn item_nullable_with(
    item: &PatternItem,
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> bool {
    if item.repeat.is_some() || item.optional.is_some() {
        return true;
    }
    if let Some(node) = &item.node {
        return nullable_rules[*rule_indices.get(node).expect("validated")];
    }
    if let Some(choice) = &item.choice {
        return choice.iter().any(|alt| {
            item_nullable_with(
                alt,
                nullable_rules,
                rule_indices,
                token_set_indices,
                expression_indices,
                expression_first,
            )
        });
    }
    let _ = expression_indices;
    let _ = expression_first;
    false
}

fn item_follow_at(
    items: &[PatternItem],
    item_index: usize,
    parent_follow: &BTreeSet<String>,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> BTreeSet<String> {
    let rest = &items[item_index + 1..];
    let mut item_follow = first_of_sequence(
        rest,
        first,
        nullable_rules,
        rule_indices,
        token_sets,
        token_set_indices,
        expression_indices,
        expression_first,
    );
    if pattern_nullable_with(
        rest,
        nullable_rules,
        rule_indices,
        token_set_indices,
        expression_indices,
        expression_first,
    ) {
        item_follow.extend(parent_follow.iter().cloned());
    }
    item_follow
}

fn collect_follow(
    items: &[PatternItem],
    parent_follow: &BTreeSet<String>,
    follow: &mut [BTreeSet<String>],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> bool {
    let mut changed = false;
    for (index, item) in items.iter().enumerate() {
        let rest = &items[index + 1..];
        let mut item_follow = first_of_sequence(
            rest,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
        if pattern_nullable_with(
            rest,
            nullable_rules,
            rule_indices,
            token_set_indices,
            expression_indices,
            expression_first,
        ) {
            item_follow.extend(parent_follow.iter().cloned());
        }
        changed |= collect_follow_for_item(
            item,
            item_follow,
            follow,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
    }
    changed
}

fn collect_follow_for_item(
    item: &PatternItem,
    item_follow: BTreeSet<String>,
    follow: &mut [BTreeSet<String>],
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> bool {
    let mut changed = false;
    if let Some(node) = &item.node {
        changed |= extend_set(
            &mut follow[*rule_indices.get(node).expect("validated")],
            item_follow,
        );
    } else if let Some(repeat) = &item.repeat {
        let mut repeat_follow = item_follow;
        repeat_follow.extend(first_of_sequence(
            repeat,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        ));
        changed |= collect_follow(
            repeat,
            &repeat_follow,
            follow,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
    } else if let Some(optional) = &item.optional {
        changed |= collect_follow(
            optional,
            &item_follow,
            follow,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
    } else if let Some(choice) = &item.choice {
        for alt in choice {
            changed |= collect_follow_for_item(
                alt,
                item_follow.clone(),
                follow,
                first,
                nullable_rules,
                rule_indices,
                token_sets,
                token_set_indices,
                expression_indices,
                expression_first,
            );
        }
    }
    changed
}

fn item_expr(
    item: &PatternItem,
    rule_index: usize,
    item_index: usize,
    item_follow: &BTreeSet<String>,
    choices: &mut Vec<GeneratedChoice>,
    sequences: &mut Vec<GeneratedSequence>,
    named_token_slices: &mut BTreeMap<String, BTreeSet<String>>,
    first: &[BTreeSet<String>],
    nullable_rules: &[bool],
    rule_indices: &HashMap<String, usize>,
    token_sets: &[BTreeSet<String>],
    token_set_indices: &HashMap<String, usize>,
    expression_indices: &HashMap<String, usize>,
    expression_first: &[BTreeSet<String>],
) -> String {
    if let Some(token) = &item.token {
        return format!("Item::Token(SyntaxKind::{token})");
    }
    if let Some(node) = &item.node {
        return format!("Item::Node({})", rule_indices.get(node).expect("validated"));
    }
    if let Some(repeat) = &item.repeat {
        let seq_name = format!("ITEM_{rule_index}_{item_index}_REPEAT_ITEMS");
        let first_name = format!("ITEM_{rule_index}_{item_index}_REPEAT_FIRST");
        let stop_name = format!("ITEM_{rule_index}_{item_index}_STOP");
        let items = repeat
            .iter()
            .enumerate()
            .map(|(nested_index, nested)| {
                item_expr(
                    nested,
                    rule_index,
                    item_index + nested_index + 1,
                    item_follow,
                    choices,
                    sequences,
                    named_token_slices,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                    expression_indices,
                    expression_first,
                )
            })
            .collect::<Vec<_>>();
        let seq_first = first_of_sequence(
            repeat,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
        sequences.push(GeneratedSequence {
            name: seq_name.clone(),
            first_name: first_name.clone(),
            items,
            first: seq_first,
        });
        named_token_slices.insert(stop_name.clone(), item_follow.clone());
        return format!(
            "Item::RepeatItems {{ items: {seq_name}, first: {first_name}, stop: {stop_name} }}"
        );
    }
    if let Some(optional) = &item.optional {
        let seq_name = format!("ITEM_{rule_index}_{item_index}_OPTIONAL_ITEMS");
        let first_name = format!("ITEM_{rule_index}_{item_index}_OPTIONAL_FIRST");
        let items = optional
            .iter()
            .enumerate()
            .map(|(nested_index, nested)| {
                item_expr(
                    nested,
                    rule_index,
                    item_index + nested_index + 1,
                    item_follow,
                    choices,
                    sequences,
                    named_token_slices,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                    expression_indices,
                    expression_first,
                )
            })
            .collect::<Vec<_>>();
        let seq_first = first_of_sequence(
            optional,
            first,
            nullable_rules,
            rule_indices,
            token_sets,
            token_set_indices,
            expression_indices,
            expression_first,
        );
        sequences.push(GeneratedSequence {
            name: seq_name.clone(),
            first_name: first_name.clone(),
            items,
            first: seq_first,
        });
        return format!("Item::OptionalItems {{ items: {seq_name}, first: {first_name} }}");
    }
    if let Some(token_set) = &item.token_set {
        return format!(
            "Item::TokenSet({})",
            token_set_indices.get(token_set).expect("validated")
        );
    }
    if let Some(expr) = &item.expr {
        return format!(
            "Item::Expr({})",
            expression_indices.get(expr).expect("validated")
        );
    }
    if let Some(choice) = &item.choice {
        let choice_name = format!("CHOICE_{}_{}", rule_index, item_index);
        let mut seen = BTreeSet::new();
        let mut alternatives = Vec::new();
        for (alt_index, alt) in choice.iter().enumerate() {
            let alt_first = first_of_item(
                alt,
                first,
                nullable_rules,
                rule_indices,
                token_sets,
                token_set_indices,
                expression_indices,
                expression_first,
            );
            let overlap = seen.intersection(&alt_first).cloned().collect::<Vec<_>>();
            assert!(
                overlap.is_empty(),
                "ambiguous choice in rule {rule_index}, item {item_index}: {overlap:?}"
            );
            seen.extend(alt_first.iter().cloned());
            alternatives.push(GeneratedAlternative {
                item_expr: item_expr(
                    alt,
                    rule_index,
                    item_index + alt_index + 1,
                    item_follow,
                    choices,
                    sequences,
                    named_token_slices,
                    first,
                    nullable_rules,
                    rule_indices,
                    token_sets,
                    token_set_indices,
                    expression_indices,
                    expression_first,
                ),
                first_name: format!("{choice_name}_ALT_{alt_index}_FIRST"),
                first: alt_first,
            });
        }
        choices.push(GeneratedChoice {
            name: choice_name.clone(),
            alternatives,
        });
        return format!("Item::Choice({choice_name})");
    }
    unreachable!("validated pattern item")
}

fn gen_ast(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("use crate::{SyntaxNode, SyntaxToken};\n");
    out.push_str(&format!(
        "use crate::generated::kind::{} as SyntaxKind;\n\n",
        grammar.language.syntax_kind
    ));
    out.push_str("pub trait AstNode: Sized {\n");
    out.push_str("    fn can_cast(kind: SyntaxKind) -> bool;\n");
    out.push_str("    fn cast(node: SyntaxNode) -> Option<Self>;\n");
    out.push_str("    fn syntax(&self) -> &SyntaxNode;\n");
    out.push_str("}\n\n");

    let mut ast_nodes = grammar
        .syntax
        .rules
        .iter()
        .filter(|rule| rule.ast)
        .map(|rule| rule.name.clone())
        .collect::<BTreeSet<_>>();
    for expression in &grammar.expressions.items {
        ast_nodes.insert(expression.root_node.clone());
        ast_nodes.extend(expression.prefix.iter().map(|item| item.node.clone()));
        ast_nodes.extend(expression.infix.iter().map(|item| item.node.clone()));
        ast_nodes.extend(expression.postfix.iter().map(|item| item.node.clone()));
        for atom in &expression.atoms {
            if let Some(node) = &atom.node {
                ast_nodes.insert(node.clone());
            }
        }
    }
    for node in &ast_nodes {
        let expr_cast_kinds = expression_cast_kinds(grammar, node);
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        out.push_str(&format!("pub struct {} {{ syntax: SyntaxNode }}\n\n", node));
        out.push_str(&format!("impl AstNode for {} {{\n", node));
        if expr_cast_kinds.is_empty() {
            out.push_str(&format!(
                "    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{} }}\n",
                node
            ));
        } else {
            let kinds = expr_cast_kinds
                .iter()
                .map(|kind| format!("SyntaxKind::{kind}"))
                .collect::<Vec<_>>()
                .join(" | ");
            out.push_str(&format!(
                "    fn can_cast(kind: SyntaxKind) -> bool {{ matches!(kind, SyntaxKind::{} | {kinds}) }}\n",
                node
            ));
        }
        out.push_str("    fn cast(node: SyntaxNode) -> Option<Self> {\n");
        out.push_str("        Self::can_cast(node.kind()).then_some(Self { syntax: node })\n");
        out.push_str("    }\n");
        out.push_str("    fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        out.push_str("}\n\n");
        out.push_str(&format!("impl {} {{\n", node));
        out.push_str("    pub fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        emit_derived_accessors(&mut out, grammar, node);
        out.push_str("}\n\n");
    }

    emit_derived_enums(&mut out, grammar);

    out.push_str("fn child<N: AstNode>(node: &SyntaxNode) -> Option<N> {\n");
    out.push_str("    node.children().find_map(N::cast)\n}\n\n");
    out.push_str("fn child_at<N: AstNode>(node: &SyntaxNode, index: usize) -> Option<N> {\n");
    out.push_str("    node.children().filter_map(N::cast).nth(index)\n");
    out.push_str("}\n\n");
    out.push_str("fn children<N: AstNode>(node: &SyntaxNode) -> Vec<N> {\n");
    out.push_str("    node.children().filter_map(N::cast).collect()\n}\n\n");
    out.push_str("fn token(node: &SyntaxNode, kind: SyntaxKind) -> Option<SyntaxToken> {\n");
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).find(|token| token.kind() == kind)\n}\n\n");
    out.push_str(
        "fn token_at(node: &SyntaxNode, kind: SyntaxKind, index: usize) -> Option<SyntaxToken> {\n",
    );
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).filter(|token| token.kind() == kind).nth(index)\n");
    out.push_str("}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("fn tokens(node: &SyntaxNode, kind: SyntaxKind) -> Vec<SyntaxToken> {\n");
    out.push_str("    tokens_matching(node, |token_kind| token_kind == kind)\n}\n\n");
    out.push_str("fn tokens_matching(node: &SyntaxNode, predicate: impl Fn(SyntaxKind) -> bool) -> Vec<SyntaxToken> {\n");
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).filter(|token| predicate(token.kind())).collect()\n}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("fn token_text(node: &SyntaxNode, kind: SyntaxKind) -> Option<String> {\n");
    out.push_str("    token(node, kind).map(|token| token.text().to_string())\n}\n\n");
    out.push_str("#[allow(dead_code)]\n");
    out.push_str("fn text_between(node: &SyntaxNode, start: SyntaxKind, end: SyntaxKind) -> Option<String> {\n");
    out.push_str("    let mut seen_start = false;\n");
    out.push_str("    let mut text = String::new();\n");
    out.push_str("    for token in node.children_with_tokens().filter_map(|element| element.into_token()) {\n");
    out.push_str("        if token.kind() == start { seen_start = true; continue; }\n");
    out.push_str("        if token.kind() == end { return seen_start.then_some(text); }\n");
    out.push_str("        if seen_start { text.push_str(token.text()); }\n");
    out.push_str("    }\n");
    out.push_str("    None\n}\n");
    out
}

fn emit_derived_accessors(out: &mut String, grammar: &Grammar, node_name: &str) {
    if let Some(rule) = grammar
        .syntax
        .rules
        .iter()
        .find(|rule| rule.name == node_name)
    {
        let mut context = AccessorContext::default();
        for item in &rule.pattern {
            emit_accessor_for_item(out, grammar, item, false, &mut context);
        }
    }
    if let Some(expression) = grammar
        .expressions
        .items
        .iter()
        .find(|expression| expression.root_node == node_name)
    {
        out.push_str(
            "    pub fn kind(&self) -> Option<ExprKind> { ExprKind::from_node(&self.syntax) }\n",
        );
        let _ = expression;
    }
    if node_name == "BinaryExpr" {
        out.push_str("    pub fn left(&self) -> Option<Expr> { self.syntax.children().filter_map(Expr::cast).next() }\n");
        out.push_str("    pub fn right(&self) -> Option<Expr> { self.syntax.children().filter_map(Expr::cast).last() }\n");
        let ops = grammar
            .expressions
            .items
            .iter()
            .flat_map(|expression| {
                expression
                    .infix
                    .iter()
                    .map(|op| format!("SyntaxKind::{}", op.token))
            })
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect::<Vec<_>>()
            .join(" | ");
        out.push_str(&format!("    pub fn op(&self) -> Option<SyntaxToken> {{ self.syntax.children_with_tokens().filter_map(|e| e.into_token()).find(|t| matches!(t.kind(), {ops})) }}\n"));
    }
    if node_name == "PrefixExpr" {
        out.push_str("    pub fn op(&self) -> Option<SyntaxToken> { self.syntax.first_token() }\n");
        out.push_str("    pub fn expr(&self) -> Option<Expr> { self.syntax.children().filter_map(Expr::cast).last() }\n");
    }
    if node_name == "CallExpr" {
        out.push_str("    pub fn callee(&self) -> Option<Expr> { self.syntax.children().filter_map(Expr::cast).next() }\n");
        out.push_str("    pub fn args(&self) -> Vec<Expr> { child::<CallArgList>(&self.syntax).map(|args| children(args.syntax())).unwrap_or_default() }\n");
    }
    if emits_text_convenience(grammar, node_name) {
        out.push_str("    pub fn text(&self) -> Option<String> { self.syntax.first_token().map(|token| token.text().to_string()) }\n");
    }
    if node_name == "PathLit" {
        out.push_str("    pub fn raw_text(&self) -> Option<String> { text_between(&self.syntax, SyntaxKind::Lt, SyntaxKind::Gt) }\n");
    }
    if node_name == "CommandHead" {
        out.push_str("    pub fn text(&self) -> Option<String> { self.name().and_then(|name| name.text()) }\n");
    }
}

#[derive(Default)]
struct AccessorContext {
    child_counts: BTreeMap<String, usize>,
    token_counts: BTreeMap<String, usize>,
}

fn emit_accessor_for_item(
    out: &mut String,
    grammar: &Grammar,
    item: &PatternItem,
    repeated: bool,
    context: &mut AccessorContext,
) {
    if let Some(label) = &item.label {
        if let Some(node) = &item.node {
            if repeated {
                out.push_str(&format!(
                    "    pub fn {label}(&self) -> Vec<{node}> {{ children(&self.syntax) }}\n"
                ));
            } else {
                let index = context.child_counts.get(node).copied().unwrap_or_default();
                out.push_str(&format!("    pub fn {label}(&self) -> Option<{node}> {{ child_at(&self.syntax, {index}) }}\n"));
            }
        } else if let Some(token) = &item.token {
            let index = context.token_counts.get(token).copied().unwrap_or_default();
            out.push_str(&format!("    pub fn {label}(&self) -> Option<SyntaxToken> {{ token_at(&self.syntax, SyntaxKind::{token}, {index}) }}\n"));
        } else if let Some(expr) = &item.expr {
            if repeated {
                out.push_str(&format!(
                    "    pub fn {label}(&self) -> Vec<{expr}> {{ children(&self.syntax) }}\n"
                ));
            } else {
                let index = context.child_counts.get(expr).copied().unwrap_or_default();
                out.push_str(&format!("    pub fn {label}(&self) -> Option<{expr}> {{ child_at(&self.syntax, {index}) }}\n"));
            }
        } else if item.choice.is_some() {
            if let Some(enum_name) = &item.r#enum {
                out.push_str(&format!("    pub fn {label}(&self) -> Option<{enum_name}> {{ {enum_name}::from_node(&self.syntax) }}\n"));
            } else if let Some(predicate) = token_choice_predicate(item) {
                out.push_str(&format!("    pub fn {label}(&self) -> Option<SyntaxToken> {{ self.syntax.children_with_tokens().filter_map(|element| element.into_token()).find(|token| {}) }}\n", predicate.replace("kind", "token.kind()")));
            }
        } else if let Some(repeat) = &item.repeat {
            if let Some(target) = repeated_target(repeat) {
                out.push_str(&format!(
                    "    pub fn {label}(&self) -> Vec<{target}> {{ children(&self.syntax) }}\n"
                ));
            } else if let Some(token_set) = repeated_token_set(repeat) {
                let tokens = ast_token_sets(grammar);
                let predicate = token_set_predicate(tokens.get(token_set).expect("validated"));
                out.push_str(&format!("    pub fn {label}(&self) -> Vec<SyntaxToken> {{ tokens_matching(&self.syntax, |kind| {predicate}) }}\n"));
            }
        } else if let Some(optional) = &item.optional {
            if let Some(target) = optional_target(optional) {
                let index = context
                    .child_counts
                    .get(target)
                    .copied()
                    .unwrap_or_default();
                out.push_str(&format!("    pub fn {label}(&self) -> Option<{target}> {{ child_at(&self.syntax, {index}) }}\n"));
            }
        }
    }
    count_fixed_item(item, context);
    if let Some(repeat) = &item.repeat {
        let mut repeat_context = AccessorContext::default();
        for item in repeat {
            emit_accessor_for_item(out, grammar, item, true, &mut repeat_context);
        }
    }
    if let Some(optional_items) = &item.optional {
        for item in optional_items {
            emit_accessor_for_item(out, grammar, item, repeated, context);
        }
    }
    if let Some(choice) = &item.choice {
        for item in choice {
            emit_accessor_for_item(out, grammar, item, repeated, context);
        }
    }
}

fn repeated_target(items: &[PatternItem]) -> Option<&str> {
    items.iter().find_map(|item| {
        item.node
            .as_deref()
            .or(item.expr.as_deref())
            .or_else(|| item.repeat.as_deref().and_then(repeated_target))
    })
}

fn optional_target(items: &[PatternItem]) -> Option<&str> {
    items
        .iter()
        .find_map(|item| item.node.as_deref().or(item.expr.as_deref()))
}

fn repeated_token_set(items: &[PatternItem]) -> Option<&str> {
    items.iter().find_map(|item| item.token_set.as_deref())
}

fn count_fixed_item(item: &PatternItem, context: &mut AccessorContext) {
    if let Some(node) = &item.node {
        *context.child_counts.entry(node.clone()).or_default() += 1;
    } else if let Some(expr) = &item.expr {
        *context.child_counts.entry(expr.clone()).or_default() += 1;
    } else if let Some(token) = &item.token {
        *context.token_counts.entry(token.clone()).or_default() += 1;
    }
}

fn token_choice_predicate(item: &PatternItem) -> Option<String> {
    let choice = item.choice.as_ref()?;
    let mut tokens = Vec::new();
    for alt in choice {
        tokens.push(alt.token.as_ref()?);
    }
    let tokens = tokens
        .into_iter()
        .map(|token| format!("SyntaxKind::{token}"))
        .collect::<Vec<_>>()
        .join(" | ");
    Some(format!("matches!(kind, {tokens})"))
}

fn emits_text_convenience(grammar: &Grammar, node_name: &str) -> bool {
    let Some(rule) = grammar
        .syntax
        .rules
        .iter()
        .find(|rule| rule.name == node_name)
    else {
        return false;
    };
    rule.pattern.len() == 1 && pattern_is_only_tokens(&rule.pattern[0])
}

fn pattern_is_only_tokens(item: &PatternItem) -> bool {
    item.token.is_some()
        || item
            .choice
            .as_ref()
            .is_some_and(|choice| choice.iter().all(pattern_is_only_tokens))
}

fn emit_derived_enums(out: &mut String, grammar: &Grammar) {
    for rule in &grammar.syntax.rules {
        for item in &rule.pattern {
            emit_enum_for_item(out, item);
        }
    }
    out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
    out.push_str("pub enum ExprKind {\n");
    let mut expr_variants = BTreeSet::new();
    for expression in &grammar.expressions.items {
        for atom in &expression.atoms {
            if let Some(node) = &atom.node {
                if expr_variants.insert(node.clone()) {
                    out.push_str(&format!("    {node}({node}),\n"));
                }
            }
        }
        for prefix in &expression.prefix {
            if expr_variants.insert(prefix.node.clone()) {
                out.push_str(&format!("    {}({}),\n", prefix.node, prefix.node));
            }
        }
        for infix in &expression.infix {
            if expr_variants.insert(infix.node.clone()) {
                out.push_str(&format!("    {}({}),\n", infix.node, infix.node));
            }
        }
        for postfix in &expression.postfix {
            if expr_variants.insert(postfix.node.clone()) {
                out.push_str(&format!("    {}({}),\n", postfix.node, postfix.node));
            }
        }
    }
    out.push_str("}\n\nimpl ExprKind {\n");
    out.push_str("    pub fn from_node(node: &SyntaxNode) -> Option<Self> {\n");
    let mut expr_casts = BTreeSet::new();
    for expression in &grammar.expressions.items {
        for node in expression
            .atoms
            .iter()
            .filter_map(|atom| atom.node.as_ref())
            .chain(expression.prefix.iter().map(|item| &item.node))
            .chain(expression.infix.iter().map(|item| &item.node))
            .chain(expression.postfix.iter().map(|item| &item.node))
        {
            if expr_casts.insert(node.clone()) {
                out.push_str(&format!("        if let Some(node) = {node}::cast(node.clone()) {{ return Some(Self::{node}(node)); }}\n"));
            }
        }
    }
    expr_casts.clear();
    out.push_str("        for child in node.children() {\n");
    for expression in &grammar.expressions.items {
        for node in expression
            .atoms
            .iter()
            .filter_map(|atom| atom.node.as_ref())
            .chain(expression.prefix.iter().map(|item| &item.node))
            .chain(expression.infix.iter().map(|item| &item.node))
            .chain(expression.postfix.iter().map(|item| &item.node))
        {
            if expr_casts.insert(node.clone()) {
                out.push_str(&format!("            if let Some(node) = {node}::cast(child.clone()) {{ return Some(Self::{node}(node)); }}\n"));
            }
        }
    }
    out.push_str("        }\n        None\n    }\n}\n\n");
}

fn emit_enum_for_item(out: &mut String, item: &PatternItem) {
    if let (Some(enum_name), Some(choice)) = (&item.r#enum, &item.choice) {
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        out.push_str(&format!("pub enum {enum_name} {{\n"));
        for alt in choice {
            if let Some(node) = &alt.node {
                out.push_str(&format!("    {node}({node}),\n"));
            }
        }
        out.push_str("}\n\n");
        out.push_str(&format!("impl {enum_name} {{\n"));
        out.push_str("    pub fn from_node(node: &SyntaxNode) -> Option<Self> {\n");
        out.push_str("        for child in node.children() {\n");
        for alt in choice {
            if let Some(node) = &alt.node {
                out.push_str(&format!("            if let Some(node) = {node}::cast(child.clone()) {{ return Some(Self::{node}(node)); }}\n"));
            }
        }
        out.push_str("        }\n        None\n    }\n}\n\n");
    }
    if let Some(repeat) = &item.repeat {
        for item in repeat {
            emit_enum_for_item(out, item);
        }
    }
    if let Some(optional) = &item.optional {
        for item in optional {
            emit_enum_for_item(out, item);
        }
    }
}

fn ast_token_sets(grammar: &Grammar) -> BTreeMap<String, BTreeSet<String>> {
    let all_tokens = grammar
        .token_names()
        .into_iter()
        .map(str::to_string)
        .collect::<BTreeSet<_>>();
    grammar
        .syntax
        .token_sets
        .iter()
        .map(|set| {
            let mut tokens = if set.include.as_deref() == Some("all_tokens") {
                all_tokens.clone()
            } else {
                set.tokens.iter().cloned().collect::<BTreeSet<_>>()
            };
            for token in &set.exclude {
                tokens.remove(token);
            }
            (set.name.clone(), tokens)
        })
        .collect()
}

fn token_set_predicate(tokens: &BTreeSet<String>) -> String {
    if tokens.is_empty() {
        return "false".to_string();
    }
    let tokens = tokens
        .iter()
        .map(|token| format!("SyntaxKind::{token}"))
        .collect::<Vec<_>>()
        .join(" | ");
    format!("matches!(kind, {tokens})")
}

fn expression_cast_kinds(grammar: &Grammar, node_name: &str) -> Vec<String> {
    let mut kinds = BTreeSet::new();
    for expression in &grammar.expressions.items {
        if expression.root_node != node_name {
            continue;
        }
        for atom in &expression.atoms {
            if let Some(node) = &atom.node {
                kinds.insert(node.clone());
            }
        }
        kinds.extend(expression.prefix.iter().map(|item| item.node.clone()));
        kinds.extend(expression.infix.iter().map(|item| item.node.clone()));
        kinds.extend(expression.postfix.iter().map(|item| item.node.clone()));
    }
    kinds.into_iter().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn toy_grammar(ast: &str) -> Grammar {
        ron::Options::default()
            .with_default_extension(ron::extensions::Extensions::IMPLICIT_SOME)
            .from_str(&format!(
                r#"(
                    version: 2,
                    language: (type_name: "ToyLanguage", syntax_kind: "ToyKind"),
                    diagnostics: (
                        invalid_token: "InvalidToken",
                        unexpected_token: "UnexpectedToken",
                        unexpected_eof: "UnexpectedEof",
                        kinds: [
                            (name: "InvalidToken", message: "invalid token"),
                            (name: "UnexpectedToken", message: "unexpected token"),
                            (name: "UnexpectedEof", message: "unexpected eof"),
                        ],
                    ),
                    tokens: (
                        rules: [
                            (name: "Whitespace", regex: "[ \n]+", trivia: skip),
                            (name: "LetKw", literal: "let"),
                            (name: "Ident", regex: "[A-Za-z_][A-Za-z0-9_]*"),
                            (name: "Int", regex: "[0-9]+"),
                            (name: "Semicolon", literal: ";"),
                        ],
                    ),
                    syntax: (
                        entry: "File",
                        nodes: ["File", "Stmt", "LetStmt", "Name"],
                        rules: [
                            (name: "File", pattern: [(label: "statements", repeat: [(node: "Stmt")])]),
                            (name: "Stmt", pattern: [(label: "kind", enum: "StmtKind", choice: [(node: "LetStmt"), (node: "Name")])]),
                            (name: "LetStmt", pattern: [(token: "LetKw"), (label: "header", repeat: [(token_set: "HeaderToken")]), (token: "Semicolon")]),
                            (name: "Name", pattern: [(label: "ident", token: "Ident")]),
                        ],
                        token_sets: [
                            (name: "HeaderToken", tokens: ["Ident", "Int"]),
                        ],
                    ),
                    expressions: (items: []),
                    ast: {ast},
                )"#
            ))
            .unwrap()
    }

    #[test]
    fn generation_includes_pratt_expression_tables_for_non_dawn_grammar() {
        let grammar: Grammar = ron::Options::default()
            .with_default_extension(ron::extensions::Extensions::IMPLICIT_SOME)
            .from_str(
                r#"(
                    version: 2,
                    language: (type_name: "ToyLanguage", syntax_kind: "ToyKind"),
                    diagnostics: (
                        invalid_token: "InvalidToken",
                        unexpected_token: "UnexpectedToken",
                        unexpected_eof: "UnexpectedEof",
                        kinds: [
                            (name: "InvalidToken", message: "invalid token"),
                            (name: "UnexpectedToken", message: "unexpected token"),
                            (name: "UnexpectedEof", message: "unexpected eof"),
                        ],
                    ),
                    tokens: (
                        rules: [
                            (name: "Whitespace", regex: "[ \n]+", trivia: skip),
                            (name: "Int", regex: "[0-9]+"),
                            (name: "Plus", literal: "+"),
                        ],
                    ),
                    syntax: (
                        entry: "File",
                        nodes: ["File"],
                        rules: [(name: "File", pattern: [(expr: "Expr")])],
                        token_sets: [],
                    ),
                    expressions: (
                        items: [
                            (
                                name: "Expr",
                                root_node: "Expr",
                                atoms: [(token: "Int")],
                                infix: [(token: "Plus", node: "BinaryExpr", precedence: "Add", associativity: "left")],
                            ),
                        ],
                    ),
                    ast: (
                        root: "File",
                        nodes: [],
                    ),
                )"#,
            )
            .unwrap();
        grammar.validate().unwrap();

        let parser = generate(&grammar)
            .into_iter()
            .find_map(|(path, text)| (path == "src/generated/parser.rs").then_some(text))
            .unwrap();
        assert!(parser.contains("Item::Expr(0)"));
        assert!(parser.contains("static EXPRESSIONS: &[Expression]"));
        assert!(parser.contains("InfixOp { token: SyntaxKind::Plus"));
    }

    #[test]
    fn generation_emits_rich_ast_accessors_and_node_enums() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [],
            )"#,
        );
        grammar.validate().unwrap();

        let ast = generate(&grammar)
            .into_iter()
            .find_map(|(path, text)| (path == "src/generated/ast.rs").then_some(text))
            .unwrap();
        assert!(ast.contains("pub fn statements(&self) -> Vec<Stmt>"));
        assert!(ast.contains("pub fn header(&self) -> Vec<SyntaxToken>"));
        assert!(ast.contains("pub enum StmtKind"));
        assert!(ast.contains("LetStmt(LetStmt)"));
        assert!(ast.contains("pub fn kind(&self) -> Option<StmtKind>"));
    }

    #[test]
    fn monarch_generation_includes_keywords_and_builtin_vocabulary() {
        let grammar = toy_grammar(
            r#"(
                root: "File",
                nodes: [],
            )"#,
        );
        grammar.validate().unwrap();
        let builtins = BuiltinsSpec {
            version: 1,
            primitives: vec!["Intensity".to_string()],
            documents: vec![BuiltinDocument {
                name: "fixture".to_string(),
                fields: vec![BuiltinField {
                    name: "channels".to_string(),
                    ty: "Range<Intensity>".to_string(),
                    cardinality: "required_one".to_string(),
                }],
            }],
            records: vec![BuiltinRecord {
                name: "FixtureType".to_string(),
                fields: Vec::new(),
            }],
        };

        let monarch = gen_monarch(&grammar, Some(&builtins));

        assert!(monarch.contains("export const dawnMonarch"));
        assert!(monarch.contains("\"let\""));
        assert!(monarch.contains("\"fixture\""));
        assert!(monarch.contains("\"channels\""));
        assert!(monarch.contains("\"FixtureType\""));
        assert!(monarch.contains("\"Intensity\""));
    }
}
