[package]
name = "dawn-runtime"
edition.workspace = true
version.workspace = true
description = "Dawn rendering runtime"
authors = ["Dawn"]
license = "MIT"

[dependencies]
dawn-language.workspace = true
indexmap.workspace = true

[dev-dependencies]
camino.workspace = true
criterion.workspace = true
dawn-project-io.workspace = true

[[bench]]
name = "render_bench"
harness = false
