// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClipId } from "./ClipId";
import type { Curve } from "./Curve";
import type { LoopMode } from "./LoopMode";
import type { TimeRange } from "./TimeRange";

/**
 * A standalone automation clip: a normalized 0-1 curve on the timeline.
 *
 * The curve maps normalized time (x: 0-1) to normalized value (y: 0-1).
 * At eval time, the engine maps the 0-1 output to the linked parameter's
 * type and range (e.g. Float min/max, Bool threshold, Int rounding).
 *
 * Requires at least 2 control points (inherited from `Curve`).
 */
export type AutomationClip = { id: ClipId, name?: string, curve: Curve, time_range: TimeRange, loop_mode: LoopMode, };
