// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The set of built-in effect types shipped with VibeLights.
 * Separated from `EffectKind` so match sites can cleanly distinguish
 * built-in dispatch from script/plugin dispatch.
 */
export type BuiltInEffect = "Solid" | "Chase" | "Rainbow" | "Strobe" | "Gradient" | "Twinkle" | "Fade" | "Wipe" | "Meteor";
