// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Universe } from "./Universe";

/**
 * Optional E1.31 universe payload size. Some controllers are configured for
 * 510-channel pixel boundaries instead of full 512-slot DMX universes.
 */
export type E131UniverseSize = { universe: Universe, size: number, };
