// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slice metadata for one fixture inside a flat frame pixel buffer.
 *
 * `start_pixel` is the fixture's first pixel index in `Frame.pixels`,
 * where each pixel occupies 4 bytes in RGBA order.
 */
export type FrameFixtureSpan = { fixture_id: number, start_pixel: number, pixel_count: number, };
