// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WordSpan } from "./WordSpan";

export type LyricsRaw = { full_text: string, language: string, words: Array<WordSpan>, };
