// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TrackItem } from "./TrackItem";

/**
 * A timeline of effects and automation clips attached to a single node
 * (fixture or group) in the element tree. Items are kept sorted by start
 * time for binary search optimization.
 */
export type NodeTimeline = { items: Array<TrackItem>, };
