// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NoteSpan = { midi_note: number, velocity: number, instrument_name: string | null, instrument_program: number | null, start: number, end: number, };
