// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BeatGridRaw } from "./BeatGridRaw";
import type { DrumAnalysis } from "./DrumAnalysis";
import type { DrumEventsRaw } from "./DrumEventsRaw";
import type { HarmonyAnalysis } from "./HarmonyAnalysis";
import type { LowLevelRaw } from "./LowLevelRaw";
import type { LyricsRaw } from "./LyricsRaw";
import type { MoodAnalysis } from "./MoodAnalysis";
import type { PitchRaw } from "./PitchRaw";
import type { SemanticRaw } from "./SemanticRaw";
import type { StemSeparationRaw } from "./StemSeparationRaw";
import type { StructureRaw } from "./StructureRaw";
import type { VocalActivityRaw } from "./VocalActivityRaw";
import type { VocalPresence } from "./VocalPresence";

export type RawAnalysisBundle = { beat_grid: BeatGridRaw | null, structure: StructureRaw | null, stems: StemSeparationRaw | null, lyrics: LyricsRaw | null, pitch: PitchRaw | null, drum_events: DrumEventsRaw | null, vocal_activity: VocalActivityRaw | null, low_level: LowLevelRaw | null, semantic: SemanticRaw | null, mood: MoodAnalysis | null, harmony: HarmonyAnalysis | null, drums: DrumAnalysis | null, vocal_presence: VocalPresence | null, };
