// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DescriptorWindow } from "./DescriptorWindow";
import type { EmbeddingTrack } from "./EmbeddingTrack";
import type { SalienceTrack } from "./SalienceTrack";

export type SemanticRaw = { embedding_tracks: Array<EmbeddingTrack>, descriptor_windows: Array<DescriptorWindow>, salience_tracks: Array<SalienceTrack>, };
