// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MotionPath } from "./MotionPath";
import type { NodeTimeline } from "./NodeTimeline";

/**
 * A sequence is the top-level timeline container. One sequence per song/show.
 * Deserialization runs `validated()` automatically via `#[serde(from = "SequenceRaw")]`.
 */
export type Sequence = { name: string, 
/**
 * Duration in seconds.
 */
duration: number, 
/**
 * Target frames per second for evaluation.
 */
frame_rate: number, 
/**
 * Audio file path, if any.
 */
audio_file: string | null, 
/**
 * Timelines keyed by element node. Each fixture or group can have its own
 * timeline of effects. Group-level effects cascade to descendant fixtures.
 */
node_timelines: { [key in string]: NodeTimeline }, 
/**
 * Named motion paths. Key = path name.
 */
motion_paths: { [key in string]: MotionPath }, };
