// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnotationLayer } from "./AnnotationLayer";

/**
 * Top-level container for all annotations associated with a song.
 *
 * Stored as `{audio_file}.annotations.json` in the media directory.
 * Contains named layers of `AnalysisDocument` data. Each layer can be
 * AI-generated or user-created, with independent marks and provenance.
 */
export type SongAnnotations = { 
/**
 * Schema version for future migration support.
 */
version: number, 
/**
 * Which layer is currently active (read by backward-compat commands).
 * `None` means no layer is selected; falls back to the first layer.
 */
active_layer: string | null, 
/**
 * Named layers in insertion order.
 */
layers: Array<[string, AnnotationLayer]>, };
