// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamedStem } from "./NamedStem";

export type StemSeparationRaw = { vocals: string | null, drums: string | null, bass: string | null, other: string | null, extra: Array<NamedStem>, };
