// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MusicalRole } from "./MusicalRole";
import type { TimeRange } from "./TimeRange";

export type UnderstandingSourceLayer = { id: string, label: string, role_hint: MusicalRole | null, confidence: number, tags: Array<string>, related_track_ids: Array<string>, time_range: TimeRange | null, instrument_name: string | null, instrument_program: number | null, note_count: number, descriptor_count: number, };
