[package]
name = "dawn-cli"
edition.workspace = true
version.workspace = true
description = "Dawn package and project command line client"
authors = ["Dawn"]
license = "MIT"

[dependencies]
camino.workspace = true
clap.workspace = true
dawn-package.workspace = true
dawn-project-io.workspace = true
keyring.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
uuid.workspace = true
webbrowser.workspace = true

[dev-dependencies]
keyring-core.workspace = true

[[bin]]
name = "dawn"
path = "src/main.rs"
