[package]
name = "dawn-cli"
edition.workspace = true
version.workspace = true
default-run = "dawn"

[dependencies]
camino.workspace = true
clap.workspace = true
deprecated-dawn-backend = { path = "../deprecated-dawn-backend" }
dawn-language = { path = "../dawn-language" }
serde.workspace = true
serde_json.workspace = true

[[bin]]
name = "dawn"
path = "src/main.rs"
