[package]
name = "dawn-desktop"
edition.workspace = true
version.workspace = true
description = "Dawn desktop"
authors = ["Dawn"]
license = "MIT"
default-run = "dawn-desktop"

[dependencies]
base64.workspace = true
camino.workspace = true
bytemuck.workspace = true
dawn-project-io.workspace = true
dawn-language.workspace = true
dawn-runtime.workspace = true
glam.workspace = true
indexmap.workspace = true
kira.workspace = true
rfd.workspace = true
serde.workspace = true
serde_json.workspace = true
specta.workspace = true
specta-typescript.workspace = true
tauri.workspace = true
tauri-specta.workspace = true
wgpu.workspace = true
yaml_serde.workspace = true

[build-dependencies]
tauri-build.workspace = true

[[bin]]
name = "dawn-desktop"
path = "src/main.rs"

[[bin]]
name = "export-bindings"
path = "src/bin/export_bindings.rs"
