[package]
name = "dawn-desktop"
edition.workspace = true
version.workspace = true
description = "Dawn desktop"
authors = ["Dawn"]
license = "MIT"
default-run = "dawn-desktop"

[dependencies]
tauri = { version = "2", features = [] }

[build-dependencies]
tauri-build = { version = "2", features = [] }

[[bin]]
name = "dawn-desktop"
path = "src/main.rs"
