// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSnapshot: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("get_snapshot")),
	openProjectDialog: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_project_dialog")),
	openProject: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_project", { path })),
	chooseNewProjectParentDirectory: () => typedError<string | null, string>(__TAURI_INVOKE("choose_new_project_parent_directory")),
	createNewProject: (parentPath: string, directoryName: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("create_new_project", { parentPath, directoryName })),
	openFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_file", { path })),
	closeFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("close_file", { path })),
	setActiveFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_active_file", { path })),
	updateActiveText: (text: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("update_active_text", { text })),
	setActiveViewMode: (mode: EditorViewModeDto) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_active_view_mode", { mode })),
	undoActiveEdit: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("undo_active_edit")),
	redoActiveEdit: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("redo_active_edit")),
	applySequenceGuiEdit: (edit: SequenceGuiEditDto) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("apply_sequence_gui_edit", { edit })),
	applySequenceSelectionEdit: (edit: SequenceSelectionEditDto) => typedError<SequenceSelectionEditResultDto, string>(__TAURI_INVOKE("apply_sequence_selection_edit", { edit })),
	chooseSequenceAudio: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("choose_sequence_audio")),
	clearSequenceAudio: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("clear_sequence_audio")),
	exportActiveSequenceFseq: (stepMs: number) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("export_active_sequence_fseq", { stepMs })),
	applyLayoutGuiEdit: (edit: LayoutGuiEditDto) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("apply_layout_gui_edit", { edit })),
	applyFixtureGuiEdit: (edit: FixtureGuiEditDto) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("apply_fixture_gui_edit", { edit })),
	flushAutosave: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("flush_autosave")),
	reloadActiveBufferFromDisk: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("reload_active_buffer_from_disk")),
	keepActiveBuffer: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("keep_active_buffer")),
	createFile: (parent: string, name: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("create_file", { parent, name })),
	createDirectory: (parent: string, name: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("create_directory", { parent, name })),
	renamePath: (path: string, newName: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("rename_path", { path, newName })),
	deletePath: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("delete_path", { path })),
	reloadProject: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("reload_project")),
	toggleProjectTree: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("toggle_project_tree")),
	setEffectPreviewEnabled: (enabled: boolean) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_effect_preview_enabled", { enabled })),
	setEffectPreviewEffects: (ids: number[]) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_effect_preview_effects", { ids })),
	openPreviewWindow: () => typedError<null, string>(__TAURI_INVOKE("open_preview_window")),
	previewPlay: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_play")),
	previewPause: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_pause")),
	previewStop: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_stop")),
	previewRewindToZero: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_rewind_to_zero")),
	previewSeek: (positionSeconds: number) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_seek", { positionSeconds })),
	setLiveOutputEnabled: (enabled: boolean) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_live_output_enabled", { enabled })),
	getPreviewScene: () => typedError<PreviewSceneDto, string>(__TAURI_INVOKE("get_preview_scene")),
	initPreviewTransport: () => typedError<null, string>(__TAURI_INVOKE("init_preview_transport")),
	disposePreviewTransport: () => typedError<null, string>(__TAURI_INVOKE("dispose_preview_transport")),
	getPreviewTransportMode: () => typedError<PreviewTransportMode, string>(__TAURI_INVOKE("get_preview_transport_mode")),
};

/* Types */
export type ActiveGuiDocumentDto = { type: "sequence"; document: SequenceDocumentDto } | { type: "layout"; document: LayoutDocumentDto } | { type: "fixture"; document: FixtureDocumentDto } | { type: "blocked"; reason: string; diagnostics: ProjectDiagnosticDto[] };

export type AppSnapshotDto = {
	projectRoot: string | null,
	projectTreeVisible: boolean,
	projectEntries: WorkspaceEntryDto[],
	tabs: EditorBufferDto[],
	activeFile: string | null,
	activeBuffer: EditorBufferDto | null,
	activeDocumentDescriptor: DocumentDescriptorDto | null,
	activeGuiDocument: ActiveGuiDocumentDto | null,
	diagnostics: ProjectDiagnosticDto[],
	status: string,
	preview: PreviewSnapshotDto,
	effectPreviewEnabled: boolean,
	liveOutput: LiveOutputSnapshotDto,
};

export type AudioPlaybackStatus = "none" | "missing" | "loading" | "loading_to_play" | "ready" | "playing" | "ended" | "error";

export type BufferExternalStateDto = "current" | "changedOnDisk" | "deletedOnDisk";

export type ColorCurvePointDto = {
	time: number,
	value: string,
};

export type DiagnosticSeverityDto = "error" | "warning";

export type DocumentDefaultObjectKeyDto = {
	view: DocumentViewIdDto,
	objectKey: string,
};

export type DocumentDescriptorDto = {
	path: string,
	objects: DocumentObjectDescriptorDto[],
	availableViews: DocumentViewIdDto[],
	defaultObjectKeys: DocumentDefaultObjectKeyDto[],
};

export type DocumentObjectDescriptorDto = {
	key: string,
	kind: ObjectKindDto,
};

export type DocumentViewIdDto = "text" | "layout" | "fixture" | "sequence";

export type EditorBufferDto = {
	path: string,
	name: string,
	text: string,
	dirty: boolean,
	externalState: BufferExternalStateDto,
	viewMode: EditorViewModeDto,
};

export type EditorViewModeDto = "text" | "gui";

export type EffectScriptReferenceDto = {
	path: string,
	effectName: string,
};

export type FixtureDefinitionDto = {
	objectKey: string,
	name: string,
	colorModel: string,
	bulbDiameterMeters: number,
	geometry: GeometryDto,
	geometrySummary: string,
	renderPlan: GeometryRenderPlanDto,
};

export type FixtureDocumentDto = {
	path: string,
	selectedObjectKey: string | null,
	fixtures: FixtureDefinitionDto[],
};

export type FixtureGuiEditDto = { type: "updateBulbDiameter"; objectKey: string; bulbDiameterMeters: number } | { type: "movePoint"; objectKey: string; pointIndex: number; point: Point3MetersDto };

export type FloatCurvePointDto = {
	time: number,
	value: number,
};

export type GeometryDto = { type: "points"; points: Point3MetersDto[] } | { type: "lines"; points: Point3MetersDto[]; pixels: number } | { type: "arc"; center: Point3MetersDto; radiusMeters: number; startDegrees: number; endDegrees: number; pixels: number };

export type GeometryRenderBoundsDto = {
	minXMeters: number,
	minYMeters: number,
	maxXMeters: number,
	maxYMeters: number,
};

export type GeometryRenderGuideDto = { type: "line"; from: GeometryRenderPointDto; to: GeometryRenderPointDto } | { type: "arc"; start: GeometryRenderPointDto; end: GeometryRenderPointDto; radiusXMeters: number; radiusYMeters: number; rotation: number; largeArc: boolean; sweepPositive: boolean };

export type GeometryRenderPlanDto = {
	emitters: GeometryRenderPointDto[],
	guides: GeometryRenderGuideDto[],
	bounds: GeometryRenderBoundsDto,
	bulbRadiusMeters: number,
};

export type GeometryRenderPointDto = {
	xMeters: number,
	yMeters: number,
	zMeters: number,
};

export type LayoutDocumentDto = {
	path: string,
	objectKey: string,
	name: string,
	renderBounds: GeometryRenderBoundsDto,
	fixtures: LayoutFixturePlacementDto[],
};

export type LayoutFixturePlacementDto = {
	id: number,
	name: string,
	transform: TransformDto,
	resolvedFixture: ResolvedLayoutFixtureDto,
};

export type LayoutGuiEditDto = { type: "updatePlacementTransform"; id: number; transform: TransformDto };

export type LayoutTargetDto = {
	kind: LayoutTargetKindDto,
	name: string,
};

export type LayoutTargetKindDto = "group" | "fixture";

export type LiveOutputSnapshotDto = {
	enabled: boolean,
	status: string,
	activeUniverseCount: number,
	lastError: string | null,
};

export type ObjectKindDto = "project" | "display" | "controller" | "layout" | "fixture" | "patch" | "sequence" | "curve" | "effect";

export type Point3MetersDto = {
	xMeters: number,
	yMeters: number,
	zMeters: number,
};

export type PreviewSceneDto = {
	generation: number,
	topologyIdentity: string,
	sourceLabel: string,
	bounds: GeometryRenderBoundsDto,
	pixelCount: number,
	fixtures: PreviewSceneFixtureDto[],
};

export type PreviewSceneFixtureDto = {
	id: number,
	name: string,
	bulbRadiusMeters: number,
	firstPixelIndex: number,
	pixels: GeometryRenderPointDto[],
};

export type PreviewSnapshotDto = {
	sourceLabel: string,
	transportState: PreviewTransportState,
	previewUpdating: boolean,
	positionSeconds: number,
	homeSeconds: number,
	durationSeconds: number,
	audio: SequenceAudioDto | null,
	clockSource: string,
	audioPlaybackStatus: AudioPlaybackStatus,
	frameTopologyIdentity: string,
	status: string,
};

export type PreviewTransportMode = "webview2_shared" | "unsupported";

export type PreviewTransportState = "stopped" | "paused" | "loading_to_play" | "playing" | "effect_preview" | "ended" | "error";

export type ProjectDiagnosticDto = {
	path: string,
	range: TextRangeDto | null,
	severity: DiagnosticSeverityDto,
	code: string,
	message: string,
};

export type ResolvedLayoutFixtureDto = {
	name: string,
	colorModel: string,
	bulbDiameterMeters: number,
	geometrySummary: string,
	renderPlan: GeometryRenderPlanDto,
	sourcePath: string,
	objectKey: string | null,
};

export type Rotation3DegreesDto = {
	xDegrees: number,
	yDegrees: number,
	zDegrees: number,
};

export type Scale3Dto = {
	x: number,
	y: number,
	z: number,
};

export type SequenceAudioDto = {
	import: string,
	resolvedPath: string,
	fileName: string,
	exists: boolean,
};

export type SequenceCurveLibraryItemDto = {
	path: string,
	objectKey: string,
	displayName: string,
	valueType: SequenceCurveValueTypeDto,
	points: SequenceCurveLibraryPointsDto,
};

export type SequenceCurveLibraryPointsDto = { type: "float"; points: FloatCurvePointDto[] } | { type: "color"; points: ColorCurvePointDto[] };

export type SequenceCurveValueTypeDto = "float" | "color";

export type SequenceDocumentDto = {
	path: string,
	objectKey: string,
	durationSeconds: number,
	frameRate: number,
	audio: SequenceAudioDto | null,
	markCollections: SequenceMarkCollectionDto[],
	lanes: SequenceLaneDto[],
	effectScripts: SequenceEffectScriptDto[],
	curveLibrary: SequenceCurveLibraryItemDto[],
	effects: SequenceEffectDto[],
	degraded: boolean,
};

export type SequenceEffectDto = {
	index: number,
	id: number,
	startSeconds: number,
	durationSeconds: number,
	target: LayoutTargetDto,
	targetLabel: string,
	scope: SequenceEffectScopeDto,
	script: string,
	scriptSource: EffectScriptReferenceDto | null,
	params: SequenceEffectParamDto[],
};

export type SequenceEffectParamCurveSourceDto = { type: "inline" } | { type: "library"; reference: string; path: string | null; objectKey: string | null; displayName: string | null };

export type SequenceEffectParamDto = {
	name: string,
	kind: SequenceEffectParamKindDto,
	options: string[],
	editable: boolean,
	value: SequenceEffectParamValueDto,
	curveSource: SequenceEffectParamCurveSourceDto | null,
};

export type SequenceEffectParamKindDto = "int" | "float" | "bool" | "color" | "enum" | "flags" | "floatCurve" | "colorCurve" | "intArray" | "floatArray" | "boolArray" | "colorArray" | "floatCurveArray" | "colorCurveArray" | "marks";

export type SequenceEffectParamValueDto = { type: "int"; value: number } | { type: "float"; value: number } | { type: "bool"; value: boolean } | { type: "color"; value: string } | { type: "enum"; value: string } | { type: "flags"; value: string[] } | { type: "floatCurve"; points: FloatCurvePointDto[] } | { type: "colorCurve"; points: ColorCurvePointDto[] } | { type: "intArray"; values: number[] } | { type: "floatArray"; values: number[] } | { type: "boolArray"; values: boolean[] } | { type: "colorArray"; values: string[] } | { type: "floatCurveArray"; values: FloatCurvePointDto[][] } | { type: "colorCurveArray"; values: ColorCurvePointDto[][] } | { type: "marks"; key: string };

export type SequenceEffectScopeDto = "perFixture" | "wholeTarget";

export type SequenceEffectScriptDto = {
	name: string,
	kind: SequenceEffectScriptKindDto,
	script: EffectScriptReferenceDto,
	import: string,
	params: SequenceEffectScriptParamDto[],
};

export type SequenceEffectScriptKindDto = "sample" | "generator";

export type SequenceEffectScriptParamDto = {
	name: string,
	kind: SequenceEffectParamKindDto,
};

export type SequenceGuiEditDto = { type: "setAudio"; import: string | null } | { type: "addEffect"; script: EffectScriptReferenceDto; target: LayoutTargetDto; scope: SequenceEffectScopeDto; startSeconds: number; markCollectionKey: string | null } | { type: "moveEffect"; id: number; startSeconds: number; target: LayoutTargetDto | null } | { type: "resizeEffect"; id: number; startSeconds: number; durationSeconds: number } | { type: "changeEffectScript"; id: number; script: EffectScriptReferenceDto } | { type: "deleteEffect"; id: number } | { type: "retargetEffect"; id: number; target: LayoutTargetDto } | { type: "setEffectScope"; id: number; scope: SequenceEffectScopeDto } | { type: "updateEffectParam"; id: number; name: string; value: SequenceEffectParamValueDto } | { type: "linkEffectCurveParam"; id: number; name: string; curvePath: string; objectKey: string } | { type: "unlinkEffectCurveParam"; id: number; name: string } | { type: "createMarkCollection"; key: string; name: string; color: string } | { type: "renameMarkCollection"; key: string; name: string } | { type: "deleteMarkCollection"; key: string } | { type: "setMarkCollectionColor"; key: string; color: string } | { type: "addMark"; collectionKey: string; timeSeconds: number } | { type: "moveMark"; collectionKey: string; index: number; timeSeconds: number } | { type: "deleteMark"; collectionKey: string; index: number };

export type SequenceLaneDto = {
	target: LayoutTargetDto,
	label: string,
};

export type SequenceMarkCollectionDto = {
	key: string,
	name: string,
	color: string,
	marksSeconds: number[],
};

export type SequenceMarkRefDto = {
	collectionKey: string,
	index: number,
};

export type SequencePasteAnchorDto = {
	laneIndex: number,
	timeSeconds: number,
};

export type SequenceResizeEdgeDto = "left" | "right";

export type SequenceSelectionDto = { type: "effects"; ids: number[] } | { type: "marks"; marks: SequenceMarkRefDto[] };

export type SequenceSelectionEditDto = { type: "copy"; selection: SequenceSelectionDto } | { type: "cut"; selection: SequenceSelectionDto } | { type: "delete"; selection: SequenceSelectionDto } | { type: "paste"; anchor: SequencePasteAnchorDto } | { type: "moveEffects"; ids: number[]; timeDeltaSeconds: number; laneDelta: number } | { type: "resizeEffects"; ids: number[]; edge: SequenceResizeEdgeDto; timeDeltaSeconds: number } | { type: "moveMarks"; marks: SequenceMarkRefDto[]; timeDeltaSeconds: number };

export type SequenceSelectionEditResultDto = {
	snapshot: AppSnapshotDto,
	selection: SequenceSelectionDto | null,
	copiedCount: number,
	skippedCount: number,
};

export type TextPositionDto = {
	line: number,
	character: number,
};

export type TextRangeDto = {
	start: TextPositionDto,
	end: TextPositionDto,
};

export type TransformDto = {
	position: Point3MetersDto,
	rotation: Rotation3DegreesDto,
	scale: Scale3Dto,
};

export type WorkspaceEntryDto = {
	path: string,
	kind: WorkspaceEntryKindDto,
	name: string,
	parent: string,
};

export type WorkspaceEntryKindDto = "directory" | "file";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (error: unknown) {
        if (error instanceof Error) throw error;
        return { status: "error", error: error as E };
    }
}

void (typedError satisfies <T, E>(result: Promise<T>) => Promise<{ status: "ok"; data: T } | { status: "error"; error: E }>);

