// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSnapshot: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("get_snapshot")),
	openProjectDialog: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_project_dialog")),
	openProject: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_project", { path })),
	openFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("open_file", { path })),
	closeFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("close_file", { path })),
	setActiveFile: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("set_active_file", { path })),
	updateActiveText: (text: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("update_active_text", { text })),
	flushAutosave: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("flush_autosave")),
	createFile: (parent: string, name: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("create_file", { parent, name })),
	createDirectory: (parent: string, name: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("create_directory", { parent, name })),
	renamePath: (path: string, newName: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("rename_path", { path, newName })),
	deletePath: (path: string) => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("delete_path", { path })),
	reloadProject: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("reload_project")),
	toggleProjectTree: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("toggle_project_tree")),
	previewPlay: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_play")),
	previewPause: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_pause")),
	previewStop: () => typedError<AppSnapshotDto, string>(__TAURI_INVOKE("preview_stop")),
};

/* Types */
export type AppSnapshotDto = {
	projectRoot: string | null,
	projectTreeVisible: boolean,
	projectEntries: WorkspaceEntryDto[],
	tabs: EditorBufferDto[],
	activeFile: string | null,
	activeBuffer: EditorBufferDto | null,
	diagnostics: ProjectDiagnosticDto[],
	status: string,
	preview: PreviewSnapshotDto,
};

export type DiagnosticSeverityDto = "error" | "warning";

export type EditorBufferDto = {
	path: string,
	name: string,
	text: string,
	dirty: boolean,
	viewMode: EditorViewModeDto,
};

export type EditorViewModeDto = "text" | "gui";

export type PreviewSnapshotDto = {
	sourceLabel: string,
	isPlaying: boolean,
	positionMs: number,
	durationMs: number,
	status: string,
};

export type ProjectDiagnosticDto = {
	path: string,
	range: TextRangeDto | null,
	severity: DiagnosticSeverityDto,
	code: string,
	message: string,
};

export type TextPositionDto = {
	line: number,
	character: number,
};

export type TextRangeDto = {
	start: TextPositionDto,
	end: TextPositionDto,
};

export type WorkspaceEntryDto = {
	path: string,
	kind: WorkspaceEntryKindDto,
	name: string,
	parent: string,
};

export type WorkspaceEntryKindDto = "directory" | "file";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

