/** Runtime access to the semantic CSS palette. CSS is the sole source of color values. */
function cssColor(name: string): string {
  const value = getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  if (value === "") throw new Error(`Missing CSS color token: ${name}`);
  return value;
}

export const THEME_COLORS = {
  background: cssColor("--dawn-bg"),
  page: cssColor("--dawn-bg-page"),
  panel: cssColor("--dawn-bg-panel"),
  rail: cssColor("--dawn-bg-rail"),
  border: cssColor("--dawn-border"),
  borderControl: cssColor("--dawn-border-control"),
  text: cssColor("--dawn-text"),
  textStrong: cssColor("--dawn-text-strong"),
  textMuted: cssColor("--dawn-text-muted"),
  textSoft: cssColor("--dawn-text-soft"),
  hover: cssColor("--dawn-hover"),
  accent: cssColor("--dawn-accent"),
  accentBackground: cssColor("--dawn-accent-bg"),
  warning: cssColor("--dawn-warning"),
  danger: cssColor("--dawn-danger"),
  dangerBackground: cssColor("--dawn-danger-bg"),
  dangerBorder: cssColor("--dawn-danger-border"),
  dangerText: cssColor("--dawn-danger-text"),
  canvasBackground: cssColor("--dawn-canvas-background"),
  canvasGuide: cssColor("--dawn-canvas-guide"),
  canvasAxis: cssColor("--dawn-canvas-axis"),
  canvasMajorGrid: cssColor("--dawn-canvas-major-grid"),
  canvasLabel: cssColor("--dawn-canvas-label"),
  automation: cssColor("--dawn-automation"),
  playhead: cssColor("--dawn-playhead"),
  markBlue: cssColor("--dawn-mark-blue"),
  markOrange: cssColor("--dawn-mark-orange"),
  markGreen: cssColor("--dawn-mark-green"),
  markPink: cssColor("--dawn-mark-pink"),
  markYellow: cssColor("--dawn-mark-yellow"),
  markRed: cssColor("--dawn-mark-red"),
  graphBlue: cssColor("--dawn-graph-blue"),
  graphRed: cssColor("--dawn-graph-red"),
  graphGreen: cssColor("--dawn-graph-green"),
  graphYellow: cssColor("--dawn-graph-yellow"),
  graphPurple: cssColor("--dawn-graph-purple"),
  graphPink: cssColor("--dawn-graph-pink"),
  white: cssColor("--dawn-white"),
  sequencePage: cssColor("--dawn-sequence-page"),
  sequencePanel: cssColor("--dawn-sequence-panel"),
  sequenceLaneAlternate: cssColor("--dawn-sequence-lane-alternate"),
  sequenceLaneSelected: cssColor("--dawn-sequence-lane-selected"),
  sequenceGrid: cssColor("--dawn-sequence-grid"),
  sequenceGridFaint: cssColor("--dawn-sequence-grid-faint"),
  timelineMajor: cssColor("--dawn-timeline-major"),
  timelineMinor: cssColor("--dawn-timeline-minor"),
  textFaint: cssColor("--dawn-text-faint"),
  overlay: cssColor("--dawn-overlay"),
  clipSelected: cssColor("--dawn-clip-selected"),
  clipHover: cssColor("--dawn-clip-hover"),
  clipBorder: cssColor("--dawn-clip-border"),
  automationFill: cssColor("--dawn-automation-fill"),
  automationGraph: cssColor("--dawn-automation-graph"),
  automationGraphGrid: cssColor("--dawn-automation-graph-grid"),
  automationGraphMajorGrid: cssColor("--dawn-automation-graph-major-grid"),
  accentSubtle: cssColor("--dawn-accent-subtle"),
  markMarqueeFill: cssColor("--dawn-mark-marquee-fill"),
  effectMarqueeFill: cssColor("--dawn-effect-marquee-fill"),
  rasterWarningOverlay: cssColor("--dawn-raster-warning-overlay"),
  emptyGradient: cssColor("--dawn-empty-gradient")
} as const;
