export type {
  DocumentUpdate,
  GuiDocumentResult,
  WorkspaceTransition,
  TransitionDecision,
  TransitionRequest,
  TransitionResult,
  ExternalConflictDecision,
  AppSnapshot,
  AppSettings,
  AudioTransportSnapshot,
  AudioTransportState,
  BufferExternalState,
  SequenceGradientStop,
  DiagnosticSeverity,
  DocumentDescriptor,
  DocumentViewId,
  EditorBuffer,
  EditorViewMode,
  SequenceEffectReference,
  PropGuiDocument,
  PropGuiEdit,
  SequenceCurvePoint,
  GeometryRenderBounds,
  GeometryRenderPoint,
  GuiDocument,
  GuiDocumentRequest,
  GuiEditCommand,
  GuiEditResult,
  PreviewGuiDocument,
  PreviewPropPlacement,
  PreviewGuiEdit,
  ElementTarget,
  LiveOutputSnapshot,
  Point3Meters,
  ProjectDiagnostic,
  PackageCacheState,
  PackageCompatibilityWarning,
  PackageDependencySource,
  PackageStatus,
  PackageDependencyStatus,
  PackageModuleStatus,
  ProjectRestoreState,
  PersistedEditorViewState,
  PersistedSequenceViewportState,
  SequenceAudio,
  SequenceAutomationClip,
  SequenceAutomationDetachmentReason,
  SequenceAutomationMapping,
  SequenceAutomationTarget,
  SequenceDetachedAutomationBinding,
  SequenceClipRaster,
  SequenceClipRasterError,
  SequenceClipRasterRequest,
  SequenceClipRasterResponse,
  SequenceCompositionGraph,
  SequenceCurveLibraryItem,
  SequenceGradientLibraryItem,
  SequenceGuiDocument,
  SequenceEffect,
  SequenceEffectParam,
  SequenceCurveSource,
  SequenceGradientSource,
  SequenceEffectParamValue,
  SequenceEffectScope,
  SequenceEffectDefinition,
  SequenceGraphEdge,
  SequenceGraphNode,
  SequenceGraphNodeKind,
  SequenceGraphOperator,
  SequenceGraphOperatorDefinition,
  SequenceGraphPortCardinality,
  SequenceGraphPortDefinition,
  SequenceGuiEdit,
  SetupGuiDocument,
  SetupGuiEdit,
  SequenceLayer,
  SequenceMarkCollection,
  SequenceMarkRef,
  SequenceSelection,
  SequenceSelectionEdit,
  SequenceSelectionEditResult,
  TextRange,
  Transform,
  WorkspaceEntry,
  WorkspaceEntryOwnership,
  WorkspaceEntryRole,
  WorkspaceExplorerState,
  WorkspaceLayoutState,
  WorkspaceOperation,
  SidebarView,
  PackageReadiness,
  ProjectSearchRequest,
  ProjectSearchResponse,
  ProjectSearchMatch,
  WorkspacePathChangePlan,
  WorkspacePathChangeRequest
} from "./generated/bindings";

export type {
  PropGuiDocument as PropDocument,
  GuiDocument as ActiveGuiDocument,
  PreviewGuiDocument as PreviewDocument,
  SequenceGuiDocument as SequenceEditorDocument,
  SetupGuiDocument as SetupDocument
} from "./generated/bindings";
