use std::fs;
use std::path::PathBuf;

use anyhow::{bail, Context, Result};
use clap::Parser;

mod spec;

use spec::Grammar;

#[derive(Debug, Parser)]
struct Args {
    #[arg(long, conflicts_with = "check")]
    write: bool,
    #[arg(long, conflicts_with = "write")]
    check: bool,
    #[arg(long, default_value = "grammar/dawn")]
    grammar: PathBuf,
    #[arg(long, default_value = "crates/dawn-syntax")]
    out: PathBuf,
}

fn main() -> Result<()> {
    let args = Args::parse();
    if !args.write && !args.check {
        bail!("pass --write or --check");
    }

    let grammar = Grammar::load(&args.grammar)?;
    grammar.validate()?;
    let files = generate(&grammar);

    if args.write {
        fs::create_dir_all(&args.out)?;
        for (name, contents) in files {
            let path = args.out.join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent)?;
            }
            fs::write(path, contents)?;
        }
        return Ok(());
    }

    let mut stale = Vec::new();
    for (name, expected) in files {
        let path = args.out.join(name);
        let actual = fs::read_to_string(&path)
            .with_context(|| format!("failed to read generated file {}", path.display()))?;
        if actual != expected {
            stale.push(name);
        }
    }

    if !stale.is_empty() {
        bail!("generated files are stale: {}", stale.join(", "));
    }
    Ok(())
}

pub fn generate(grammar: &Grammar) -> Vec<(&'static str, String)> {
    vec![
        ("src/generated/diagnostic.rs", gen_diagnostic(grammar)),
        ("src/generated/kind.rs", gen_kind(grammar)),
        ("src/generated/lexer.rs", gen_lexer(grammar)),
        ("src/generated/parser.rs", gen_parser(grammar)),
        ("src/generated/ast.rs", gen_ast(grammar)),
    ]
}

fn header() -> &'static str {
    "// @generated by dawn-syntax-gen. Do not edit by hand.\n\n"
}

fn gen_diagnostic(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    out.push_str("pub enum DiagnosticKind {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!("    {},\n", diagnostic.name));
    }
    out.push_str("}\n\n");
    out.push_str("impl DiagnosticKind {\n");
    out.push_str("    pub fn message(self) -> &'static str {\n");
    out.push_str("        match self {\n");
    for diagnostic in &grammar.diagnostics.kinds {
        out.push_str(&format!(
            "            Self::{} => {:?},\n",
            diagnostic.name, diagnostic.message
        ));
    }
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::fmt::Display for DiagnosticKind {\n");
    out.push_str("    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {\n");
    out.push_str("        f.write_str(self.message())\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("impl std::error::Error for DiagnosticKind {}\n");
    out
}

fn gen_kind(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str("#[repr(u16)]\npub enum SyntaxKind {\n");
    for name in grammar.syntax_kinds() {
        out.push_str("    ");
        out.push_str(name);
        out.push_str(",\n");
    }
    out.push_str("    Error,\n}\n\n");
    out.push_str("impl SyntaxKind {\n");
    out.push_str("    pub fn is_doc_kind(self) -> bool {\n");
    out.push_str("        matches!(self, ");
    out.push_str(
        &grammar
            .syntax
            .doc_kinds
            .iter()
            .map(|(_, token)| format!("Self::{token}"))
            .collect::<Vec<_>>()
            .join(" | "),
    );
    out.push_str(")\n    }\n\n");
    out.push_str("    pub fn is_trivia(self) -> bool {\n");
    out.push_str("        matches!(self, ");
    out.push_str(
        &grammar
            .tokens
            .trivia
            .iter()
            .map(|trivia| format!("Self::{}", trivia.name))
            .collect::<Vec<_>>()
            .join(" | "),
    );
    out.push_str(")\n    }\n}\n\n");
    out.push_str("impl From<SyntaxKind> for rowan::SyntaxKind {\n");
    out.push_str("    fn from(kind: SyntaxKind) -> Self {\n");
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n");
    out.push_str("}\n\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]\n");
    out.push_str("pub enum DawnLanguage {}\n\n");
    out.push_str("impl rowan::Language for DawnLanguage {\n");
    out.push_str("    type Kind = SyntaxKind;\n\n");
    out.push_str("    fn kind_from_raw(raw: rowan::SyntaxKind) -> Self::Kind {\n");
    out.push_str("        assert!(raw.0 <= SyntaxKind::Error as u16);\n");
    out.push_str("        unsafe { std::mem::transmute::<u16, SyntaxKind>(raw.0) }\n");
    out.push_str("    }\n\n");
    out.push_str("    fn kind_to_raw(kind: Self::Kind) -> rowan::SyntaxKind {\n");
    out.push_str("        rowan::SyntaxKind(kind as u16)\n");
    out.push_str("    }\n}\n");
    out
}

fn gen_lexer(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str(include_str!("templates/lexer.rs"));
    out = out.replace("/*KEYWORD_MATCH*/", &keyword_match(grammar));
    out = out.replace("/*PUNCTUATION_MATCH*/", &punctuation_match(grammar));
    out
}

fn keyword_match(grammar: &Grammar) -> String {
    grammar
        .tokens
        .keywords
        .iter()
        .map(|(kind, text)| format!("        {text:?} => SyntaxKind::{kind},\n"))
        .collect::<String>()
}

fn punctuation_match(grammar: &Grammar) -> String {
    let mut punctuation = grammar.tokens.punctuation.clone();
    punctuation.sort_by(|left, right| right.1.len().cmp(&left.1.len()));
    punctuation
        .into_iter()
        .map(|(kind, text)| format!("        ({text:?}, Some((SyntaxKind::{kind}, {len}))),\n", len = text.len()))
        .collect::<String>()
}

fn gen_parser(_grammar: &Grammar) -> String {
    format!("{}{}", header(), include_str!("templates/parser.rs"))
}

fn gen_ast(grammar: &Grammar) -> String {
    let mut out = String::from(header());
    out.push_str("use crate::{SyntaxNode, SyntaxToken};\n");
    out.push_str("use crate::generated::kind::SyntaxKind;\n\n");
    out.push_str("pub trait AstNode: Sized {\n");
    out.push_str("    fn can_cast(kind: SyntaxKind) -> bool;\n");
    out.push_str("    fn cast(node: SyntaxNode) -> Option<Self>;\n");
    out.push_str("    fn syntax(&self) -> &SyntaxNode;\n");
    out.push_str("}\n\n");

    for node in &grammar.ast.nodes {
        out.push_str("#[derive(Debug, Clone, PartialEq, Eq)]\n");
        out.push_str(&format!("pub struct {} {{ syntax: SyntaxNode }}\n\n", node.name));
        out.push_str(&format!("impl AstNode for {} {{\n", node.name));
        out.push_str(&format!(
            "    fn can_cast(kind: SyntaxKind) -> bool {{ kind == SyntaxKind::{} }}\n",
            node.syntax
        ));
        out.push_str("    fn cast(node: SyntaxNode) -> Option<Self> {\n");
        out.push_str("        Self::can_cast(node.kind()).then_some(Self { syntax: node })\n");
        out.push_str("    }\n");
        out.push_str("    fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        out.push_str("}\n\n");
        out.push_str(&format!("impl {} {{\n", node.name));
        out.push_str("    pub fn syntax(&self) -> &SyntaxNode { &self.syntax }\n");
        for accessor in &node.accessors {
            match accessor.kind.as_str() {
                "child" => {
                    let target = accessor.node.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<{}> {{ child(&self.syntax) }}\n",
                        accessor.name, target
                    ));
                }
                "children" => {
                    let target = accessor.node.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Vec<{}> {{ children(&self.syntax) }}\n",
                        accessor.name, target
                    ));
                }
                "first_token" => {
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<SyntaxToken> {{ self.syntax.first_token() }}\n",
                        accessor.name
                    ));
                }
                "token" => {
                    let token = accessor.token.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<SyntaxToken> {{ token(&self.syntax, SyntaxKind::{}) }}\n",
                        accessor.name, token
                    ));
                }
                "text_between" => {
                    let start = accessor.start.as_ref().expect("validated");
                    let end = accessor.end.as_ref().expect("validated");
                    out.push_str(&format!(
                        "    pub fn {}(&self) -> Option<String> {{ text_between(&self.syntax, SyntaxKind::{}, SyntaxKind::{}) }}\n",
                        accessor.name, start, end
                    ));
                }
                _ => {}
            }
        }
        out.push_str("}\n\n");
    }

    for ast_enum in &grammar.ast.enums {
        out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
        out.push_str(&format!("pub enum {} {{\n", ast_enum.name));
        for (variant, _) in &ast_enum.variants {
            out.push_str(&format!("    {},\n", variant));
        }
        out.push_str("}\n\n");
        out.push_str(&format!("impl {} {{\n", ast_enum.name));
        out.push_str("    pub fn from_token(kind: SyntaxKind) -> Option<Self> {\n");
        out.push_str("        Some(match kind {\n");
        for (variant, token) in &ast_enum.variants {
            out.push_str(&format!("            SyntaxKind::{} => Self::{},\n", token, variant));
        }
        out.push_str("            _ => return None,\n");
        out.push_str("        })\n    }\n}\n\n");
    }

    out.push_str("fn child<N: AstNode>(node: &SyntaxNode) -> Option<N> {\n");
    out.push_str("    node.children().find_map(N::cast)\n}\n\n");
    out.push_str("fn children<N: AstNode>(node: &SyntaxNode) -> Vec<N> {\n");
    out.push_str("    node.children().filter_map(N::cast).collect()\n}\n\n");
    out.push_str("fn token(node: &SyntaxNode, kind: SyntaxKind) -> Option<SyntaxToken> {\n");
    out.push_str("    node.children_with_tokens().filter_map(|element| element.into_token()).find(|token| token.kind() == kind)\n}\n\n");
    out.push_str("fn text_between(node: &SyntaxNode, start: SyntaxKind, end: SyntaxKind) -> Option<String> {\n");
    out.push_str("    let mut seen_start = false;\n");
    out.push_str("    let mut text = String::new();\n");
    out.push_str("    for token in node.children_with_tokens().filter_map(|element| element.into_token()) {\n");
    out.push_str("        if token.kind() == start { seen_start = true; continue; }\n");
    out.push_str("        if token.kind() == end { return seen_start.then_some(text); }\n");
    out.push_str("        if seen_start { text.push_str(token.text()); }\n");
    out.push_str("    }\n");
    out.push_str("    None\n}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_and_validates_dawn_grammar() {
        let grammar = Grammar::load(&workspace_root().join("grammar/dawn")).unwrap();
        grammar.validate().unwrap();
    }

    #[test]
    fn generated_files_have_headers() {
        let grammar = Grammar::load(&workspace_root().join("grammar/dawn")).unwrap();
        grammar.validate().unwrap();
        for (name, contents) in generate(&grammar) {
            assert!(
                contents.starts_with("// @generated by dawn-syntax-gen. Do not edit by hand.")
                    || contents.starts_with("# @generated by dawn-syntax-gen. Do not edit by hand."),
                "{name} is missing generated header"
            );
        }
    }

    #[test]
    fn check_detects_stale_generated_output() {
        let grammar = Grammar::load(&workspace_root().join("grammar/dawn")).unwrap();
        grammar.validate().unwrap();
        let dir = tempfile::tempdir().unwrap();

        for (name, contents) in generate(&grammar) {
            let path = dir.path().join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, contents).unwrap();
        }
        fs::write(dir.path().join("src/generated/kind.rs"), "stale").unwrap();

        let stale = generate(&grammar)
            .into_iter()
            .filter(|(name, expected)| fs::read_to_string(dir.path().join(name)).unwrap() != *expected)
            .map(|(name, _)| name)
            .collect::<Vec<_>>();

        assert_eq!(stale, vec!["src/generated/kind.rs"]);
    }

    fn workspace_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf()
    }
}
