// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisProvenance } from "./AnalysisProvenance";
import type { AudioUnderstanding } from "./AudioUnderstanding";
import type { MarkTimeline } from "./MarkTimeline";
import type { RawAnalysisBundle } from "./RawAnalysisBundle";

export type AnalysisDocument = { version: number, raw: RawAnalysisBundle, marks: MarkTimeline | null, understanding: AudioUnderstanding | null, provenance: AnalysisProvenance, };
