// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Boolean flags for which analysis stages to run.
 */
export type AnalysisFeatures = { beats: boolean, structure: boolean, stems: boolean, lyrics: boolean, mood: boolean, harmony: boolean, low_level: boolean, pitch: boolean, drums: boolean, vocal_presence: boolean, };
