// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Provenance labels for which raw analysis sources contributed to a mark track.
 */
export type AnalysisFeatureKind = "beats" | "structure" | "semantic" | "mood" | "harmony" | "lyrics" | "pitch" | "drums" | "vocal_presence" | "low_level" | "stems";
