// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRunInfo } from "./ModelRunInfo";
import type { UserEditRecord } from "./UserEditRecord";

export type AnalysisProvenance = { generated_at: string | null, pipeline_version: string | null, models: Array<ModelRunInfo>, source_audio_path: string | null, source_audio_hash: string | null, gpu_used: boolean, user_edits: Array<UserEditRecord>, };
