// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisDocument } from "./AnalysisDocument";
import type { LayerOrigin } from "./LayerOrigin";

/**
 * A single named layer of analysis/annotation data.
 *
 * Both AI-generated and user-created layers share the same structure:
 * an `AnalysisDocument`. This keeps raw model output, planner-facing marks,
 * and provenance together under the same editable layer abstraction.
 */
export type AnnotationLayer = { 
/**
 * Display name (also the key in `SongAnnotations.layers`).
 */
name: string, 
/**
 * Whether this layer was produced by AI or created by a user.
 */
origin: LayerOrigin, 
/**
 * The analysis/annotation data for this layer.
 */
data: AnalysisDocument, };
