// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnderstandingDescriptor } from "./UnderstandingDescriptor";
import type { UnderstandingHypothesis } from "./UnderstandingHypothesis";
import type { UnderstandingSourceLayer } from "./UnderstandingSourceLayer";

export type AudioUnderstanding = { version: number, summary: string | null, focus_prompt: string | null, descriptors: Array<UnderstandingDescriptor>, source_layers: Array<UnderstandingSourceLayer>, hypotheses: Array<UnderstandingHypothesis>, };
