// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BeatGridRaw = { beats: Array<number>, downbeats: Array<number>, subdivisions_8: Array<number>, subdivisions_16: Array<number>, tempo_bpm: number, beat_confidences: Array<number>, tempo_confidence: number, time_signature_num: number, };
