// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { E131UniverseSize } from "./E131UniverseSize";
import type { Universe } from "./Universe";

/**
 * How a controller communicates with the sequencer.
 */
export type ControllerProtocol = { "E131": { unicast_address: string | null, universes: Array<Universe>, universe_sizes?: Array<E131UniverseSize>, } } | { "ArtNet": { address: string | null, } } | { "Serial": { port: string, baud_rate: number, } } | "Unknown";
