// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CurveMarkKind = "energy" | "tension" | "rhythmic_density" | "spectral_brightness" | "spectral_noisiness" | "lead_salience" | "bass_salience" | "vocal_salience" | "stereo_width";
