// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurveMarkKind } from "./CurveMarkKind";
import type { MarkSource } from "./MarkSource";

export type CurveTrack = { id: string, name: string, kind: CurveMarkKind, source: MarkSource | null, confidence: number, sample_rate_hz: number, values: Array<number>, };
