// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DescriptorWindow = { tags: Array<string>, confidence: number | null, start: number, end: number, };
