// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventHit } from "./EventHit";

export type DrumEventsRaw = { kicks: Array<EventHit>, snares: Array<EventHit>, hats: Array<EventHit>, other_hits: Array<EventHit>, };
