// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectKind = "Solid" | "Chase" | "Rainbow" | "Strobe" | "Gradient" | "Twinkle" | "Fade" | "Wipe" | "Meteor" | { "Script": string };
