// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmbeddingTrack = { id: string, name: string, model: string | null, sample_rate_hz: number, dimensions: number, values: Array<number>, };
