// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnalysisFeatureKind } from "./AnalysisFeatureKind";
import type { MarkDomain } from "./MarkDomain";
import type { MarkSource } from "./MarkSource";
import type { MusicalRole } from "./MusicalRole";
import type { PointMark } from "./PointMark";

export type EventTrack = { id: string, name: string, domain: MarkDomain, role: MusicalRole | null, source: MarkSource | null, confidence: number, derived_from: Array<AnalysisFeatureKind>, events: Array<PointMark>, };
