// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameFixtureSpan } from "./FrameFixtureSpan";

/**
 * A single frame of output as a flat RGBA pixel buffer.
 *
 * Pixels are laid out fixture-by-fixture. All fixtures that appear in the
 * preview layout come first in layout order, followed by any remaining
 * fixtures in show order. This gives the preview renderer a contiguous prefix
 * it can draw directly, while still preserving per-fixture spans for output.
 */
export type Frame = { 
/**
 * Flat RGBA byte buffer for the entire frame.
 */
pixels: Array<number>, 
/**
 * Per-fixture spans inside `pixels`.
 */
fixture_spans: Array<FrameFixtureSpan>, 
/**
 * Diagnostic warnings when the frame is empty for a known reason
 * (e.g. missing sequence, no node timelines). `None` when there is nothing to report.
 */
warnings?: Array<string>, };
