// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChordEvent } from "./ChordEvent";

export type HarmonyAnalysis = { key: string, key_confidence: number, chords: Array<ChordEvent>, };
