// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an annotation layer was produced by AI analysis or by a user.
 */
export type LayerOrigin = "ai" | "user";
