// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarkTrack } from "./MarkTrack";

export type MarkTimeline = { version: number, tracks: Array<MarkTrack>, };
