// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarkDomain = "grid" | "rhythm" | "melody" | "bass" | "vocal" | "texture" | "structure" | "cue";
