// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CurveTrack } from "./CurveTrack";
import type { EventTrack } from "./EventTrack";
import type { SpanTrack } from "./SpanTrack";

export type MarkTrack = { "track_type": "events" } & EventTrack | { "track_type": "spans" } & SpanTrack | { "track_type": "curve" } & CurveTrack;
