// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MarkSource = "mix" | "vocals_stem" | "drums_stem" | "bass_stem" | "other_stem" | "model" | "user" | "derived";
