// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelRunInfo = { stage: string, model_name: string, model_version: string | null, provider: string | null, };
