// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MusicalRole = "lead" | "support" | "bass" | "drums" | "vocal" | "pad" | "fx";
