// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FixtureId } from "./FixtureId";
import type { GroupId } from "./GroupId";

/**
 * Identifies a node in the element tree. Each fixture or group can have
 * its own timeline of effects. Effects on a group node cascade to all
 * descendant fixtures.
 */
export type NodeId = { "Fixture": FixtureId } | { "Group": GroupId };
