// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PointMarkKind } from "./PointMarkKind";

export type PointMark = { id: string, kind: PointMarkKind, time: number, strength: number | null, confidence: number | null, tags: Array<string>, };
