// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PointMarkKind = "beat" | "downbeat" | "subdivision8" | "subdivision16" | "kick" | "snare" | "hat" | "bass_hit" | "melody_onset" | "vocal_onset" | "accent" | "impact" | "fill_hit";
