// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SalienceTrack = { id: string, name: string, sample_rate_hz: number, values: Array<number>, };
