// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SectionLabelSpan = { label: string, confidence: number, start: number, end: number, };
