// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpanMarkKind } from "./SpanMarkKind";

export type SpanMark = { id: string, kind: SpanMarkKind, strength: number | null, confidence: number | null, tags: Array<string>, start: number, end: number, };
