// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpanMarkKind = "note" | "section_intro" | "section_verse" | "section_chorus" | "section_bridge" | "section_drop" | "phrase" | "build" | "breakdown" | "lead_phrase" | "vocal_phrase" | "texture_window" | "sustain" | "call" | "response";
