// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhraseSpan } from "./PhraseSpan";
import type { SectionLabelSpan } from "./SectionLabelSpan";

export type StructureRaw = { sections: Array<SectionLabelSpan>, phrases: Array<PhraseSpan>, };
