// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutomationClip } from "./AutomationClip";
import type { EffectInstance } from "./EffectInstance";

/**
 * A single item on a track: either an effect or an automation clip.
 * Items are stored sorted by start time for binary search.
 */
export type TrackItem = { "item_type": "Effect" } & EffectInstance | { "item_type": "Clip" } & AutomationClip;
