// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UnderstandingHypothesisKind = "source_role" | "texture" | "motion" | "phrase" | "descriptor" | "instrument_layer";
