// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

export type UnderstandingDescriptor = { id: string, label: string, tags: Array<string>, confidence: number | null, time_range: TimeRange, };
