// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";
import type { UnderstandingHypothesisKind } from "./UnderstandingHypothesisKind";

export type UnderstandingHypothesis = { id: string, label: string, kind: UnderstandingHypothesisKind, confidence: number, tags: Array<string>, related_track_ids: Array<string>, time_range: TimeRange | null, };
