// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EventHit } from "./EventHit";
import type { PhraseSpan } from "./PhraseSpan";

export type VocalActivityRaw = { segments: Array<PhraseSpan>, onsets: Array<EventHit>, };
